Ajout de l'Aide à la Garde d'Enfant pour les Hauts de France
openfisca/openfisca-france-local pull request #130
Opened 2022-06-01 15:24 UTC by Cugniere

Ajout de l'Aide à la Garde d'Enfant pour les Hauts de France

2022-06-01 15:45 UTC, Kout95 requested changes

2022-10-19 09:51 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +class aide_garde_enfant(Variable):
L'aide étant limitée à la région haut de france, ne serait-il pas préferable d'avoir un nom de classe précsant l'info pour éviter les confusions?

2023-02-13 13:16 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        eligibilite_geographique = sum([startswith(depcom, code_departement) for code_departement in code_departements])
Résolu avec l'ajout de la variable ŕegions dans OF-France. (Variable qui se base sur le `depcom` de la famille pour déterminer la région de résidence).

2023-02-13 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        enfants_eligibles = (age < params.age_maximum_enfant)
Dans les critère détaillés sur [le site hautsdefrance.fr](https://guide-aides.hautsdefrance.fr/aide636), il est expliqué que l'aide s'arrêtera le mois suivant l'anniversaire des 3 ans.
Une évaluation de ce critère sera plus précise si on utilise la variable `age_en_mois` <= 36 (à modifier dans le fichier paramètre ou bien l'interpréter)

2023-02-13 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        eligibilite_geographique = sum(
Nous vérifions ici l'éligibilité résidentielle du foyer mais pas le faut que les enfants sont gardés dans la régions ou dans une région limitrophe.
Il me semble possible de le négliger mais necessite vérifications.

2023-02-13 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        eligibilite_revenus = rfr < plafond_ressources
Commentaire toujours valable.
La seule question dont il faut être sûr c'est de savoir si on parle bien de SMIC brut (ce qui est probable car le net n'est pas calculable génériquement).

2023-02-13 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +    def formula(famille, period, parameters):
Cette formule ne prend pas en compte les critères suivants : 
- La durée de la garde doit correspondre à au moins 20 heures par semaine.
- La (les) garde.s d'enfant.s doivent avoir le statu de `Garde déclarée` (agrée par CAF)

Il est necessaire de déterminer l'importance de ces  critères et leur faisabilité technique.

2023-02-15 17:59 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +    def formula(famille, period, parameters):
Confirmé négligeable.

2023-03-14 17:26 UTC, guillett approved these changes
Je valide pour éviter d'être bloquant, cela étant dit, ça serait chouette
- de remplacer les 36 mois en 3 ans
- de faire apparaître les critères non pris en compte dans un commentaire en début de formule.

2023-03-15 10:50 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        enfants_eligibles = (age < params.age_maximum_enfant)
`L'aide s'arrête le mois qui suit l'anniversaire des 3 ans de l'enfant`

Cette condition implique qu'une famille avec un enfant de `3 ans et 1 mois` **ne pourra pas** bénéficier de l'aide.

Si la comparaison de l'age est faite avec une précision en année, une simulation par cette même famille renverra une éligibilité de la famille pour l'aide à la garde d'enfant, à tort.

D'après mes expérimentation, Openfisca considère qu'en enfant agé de 47 mois (donc 3 ans et 11 mois) a 3 ans, donc éligible, ce qui est **faux**.

2023-03-16 08:36 UTC, guillett commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        enfants_eligibles = (age < params.age_maximum_enfant)
Mais `< 3 ans` fonctionnerait, non ?

2023-03-16 10:03 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/hauts_de_france/aide_garde_enfant.py
> +        enfants_eligibles = (age < params.age_maximum_enfant)
Euh... oui en effet -__-' :D 
Merci!

2023-03-16 10:26 UTC, merged