Réforme Aides jeunes - Ajouts d'aide YAML à la volée
openfisca/openfisca-france-local pull request #137
Opened 2022-12-22 15:04 UTC by Allan-CodeWorks

Cette modification permet d'ajouter des variables à OpenFisca a partir d'aides sociales modélisées en YAML.
L'objectif initial est d'intégrer les aides déjà modélisées dans le dépôt [aides-jeunes](https://github.com/betagouv/aides-jeunes).

2023-01-04 07:54 UTC, guillett requested changes
C'est top, les fichiers pour les régions vont disparaitre et simplfiier cette PR.

Il faudrait remplacer les `period.*_month` par `period` pour alléger.

Ça serait bien aussi que tu testes l'utilisation de cette réforme via la web API.

On devrait pouvoir la merger en l'état.

Mais je note tout de même un point d'attention / pour la prochaine itération (la suite est donc hors scope de cette PR :) ) :
Que ce passe-t-il si une aide YAML n'est pas bien formatée ? Par là, je vais dire si, par exemple, une valeur de `mention_baccalaureat` vaut `YOLO` ?
Est ce que ça plante ?
À quel moment ?
Est ce que ça pourrait être à un autre moment ?
Est ce que ça serait bien ?

> AKA Lancement de discussion :)

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    return sum([current_year == TypesClasse[value] for value in condition['values']])
```suggestion
    return sum([current_year == TypesClasse[value] for value in condition['values']]) > 0
```

Pour éviter des effets de bord

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    individus_age = individu('age', period.first_month)
```suggestion
    individus_age = individu('age', period)
```

Pour alléger le code, je ferais l'hypothèse que `period` est un mois.

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    depcom = individu.menage('depcom', period.first_month)
```suggestion
    depcom = individu.menage('depcom', period)
```

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    return sum([individu.menage(eligibilite_region_table[code_region], period.first_month) for code_region in condition['values']])
```suggestion
    return sum([individu.menage(eligibilite_region_table[code_region], period) for code_region in condition['values']])
```

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_region_eligible(individu: Population, period: Period, condition):
Tu pourras faire un refactor avec la PR sur France.

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    rfr = individu.foyer_fiscal('rfr', period.this_year)
:+1:

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +        'groupe_specialites_formation', period.first_month)
```suggestion
        'groupe_specialites_formation', period)
```

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +        'annee_etude', period.first_month)
```suggestion
        'annee_etude', period)
```

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    return sum([has_mention == TypesMention[value] for value in condition['values']])
```suggestion
    return sum([has_mention == TypesMention[value] for value in condition['values']]) > 0
```

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_to_implement(individu: Population, period: Period) -> np.array:
Peut être supprimé ?

2023-01-04 07:54 UTC, guillett commented on openfisca_france_local/parameters/aides_jeunes.yaml
> +etat_eligibilite_bafa:
Ce fichier est encore utilisé ? J'ai l'impression que c'est un reliquat de test.

2023-01-26 10:50 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/aides_jeunes.yaml
> +etat_eligibilite_bafa:
Effectivement, merci!

2023-01-26 11:09 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_region_eligible(individu: Population, period: Period, condition):
Oui, c'est fait.

2023-01-26 11:13 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_to_implement(individu: Population, period: Period) -> np.array:
Tout à fait, merci!

2023-01-26 11:15 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        "value_type": float,  # hardcoded
Le fait que cette ligne soit toujours en dur me pose question et je n'arrive pas à voir les conséquences.

2023-01-26 11:16 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        "entity": Individu,
Le fait que cette ligne soit également toujours en dur me pose question et je n'arrive pas à voir les conséquences.

2023-03-06 17:02 UTC, guillett reviewed
En pending !!!! :sweat_smile:

2023-03-07 08:03 UTC, Allan-CodeWorks commented on tests/regions/nouvelle-aquitaine/eligibilite_residentielle.yml
> +- period: 2022-11
Done : 
https://github.com/openfisca/openfisca-france-local/pull/146

2023-03-07 08:04 UTC, Allan-CodeWorks commented on tests/regions/occitanie/eligibilite_residentielle.yml
> +    depcom: ["31555", "95563"]
Done : 
https://github.com/openfisca/openfisca-france-local/pull/146

2023-03-07 08:07 UTC, Allan-CodeWorks commented on setup.py
> +        'OpenFisca-France >= 139.0.0, < 140.0.0',
Pourquoi? 
Nous utilisons la variable `region` qui n'éxiste pas avant la version `139.0.0` d'OpenFisca France.
Si une version antérieur à la version 139 est utilisée, toutes les aides conditionées par une résidence régionale donneront une erreur.

2023-03-07 08:07 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/occitanie/eligibilite_residentielle.py
> +    b'09', b'11', b'12', b'30', b'31', b'32', b'34', b'46', b'48', b'65', b'66', b'81', b'82'
Done : 
https://github.com/openfisca/openfisca-france-local/pull/146

2023-03-07 08:14 UTC, Allan-CodeWorks commented on benefits/test_condition_beneficiaire_rsa.yaml
> +    conditions: []
Par contre, pour le champs `conditions_generales` vient à manquer, on a un crash au build.

2023-03-07 08:20 UTC, Allan-CodeWorks commented on benefits/test-age-condition.yaml
> +label: aide conditionee par age
Effectivement, merci c'est corrigé.

2023-03-07 08:21 UTC, Allan-CodeWorks commented on benefits/test-condition_departements.yaml
> +label: aide locale au BAFA pour une session de formation générale
Effectivement, merci c'est corrigé.

2023-03-08 09:46 UTC, guillett reviewed
:warning: j'ai push un commit pour faire un test.

Je m'attends à ce que cette commande (ajustée à ton environnement) fonctionne mais ce n'est pas le cas.

>OFFL_TEST_BENEFIT_PATH=/home/thomas/repos/aides-jeunes/data/benefits/javascript openfisca test tests/test_aides_jeunes_reform.py

Sur `master` côté Aides Jeunes, j'ai cette erreur

> E           KeyError: "field 'epcis' missing in file: /home/thomas/repos/aides-jeunes/data/benefits/javascript/intercommunalite_bordeaux-tarification-solidaire-des-transports.yml"

2023-03-08 09:46 UTC, guillett commented on benefits/test_condition_communes.yaml
> +    values:
Euh, on a besoin d'une aussi longue liste ?

2023-03-08 09:46 UTC, guillett commented on setup.py
> +        'OpenFisca-France >= 139.0.0, < 140.0.0',
Ah oui désolé, je me suis trompé. C'est bien du coup de merger la PR sur les régions avant pour expliciter que les dépendances ne devraient pas changer.

2023-03-08 12:50 UTC, Allan-CodeWorks commented on benefits/test_condition_communes.yaml
> +    values:
Euh, non :D

2023-03-09 13:40 UTC, Allan-CodeWorks commented
Je n'étais pas à jour au niveau des fichiers d'aides.
De nouvelles aides avec des conditions non implantées ont été ajoutées.
Elles sont maintenant gérées. J'en ai profité pour affiner les messages d'erreurs en cas de condition ou profil non géré.
Dans ton cas, on aurait maintenant : 
```
KeyError: 'Condition: `epcis` is unknown - Input file: benefits/test_condition_taux_incapacite.yaml'
```

2023-03-14 15:55 UTC, guillett approved these changes
J'ai fait deux commits, @Allan-CodeWorks je te laisse regarder et comprendre de ton côté si c'est bon pour toi tu peux merger. :tada:

2023-03-15 09:44 UTC, merged