CI Ajout naif test version mini IF
openfisca/openfisca-france-local pull request #145
Opened 2023-02-27 14:34 UTC by Allan-CodeWorks

2023-03-09 16:29 UTC, Allan-CodeWorks commented on .github/workflows/workflow.yml
> +          key: build-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ github.sha }}-maximal
Petit point d'attention ici parce que ne sait pas trop comment tester.
Ayant modifié la `key` référence pour les actions de `cache`, je suppose que ce code devrait récupérer l'environnement avec les dépendances en version maximale, mais j'aimerai un autre regard.

(Remarque valable pour la ligne 128 également)

2023-03-13 10:44 UTC, Allan-CodeWorks commented on get_minimal_version.py
> +        print(f'OpenFisca-Core=={min_version}')
OH oui c'est bien mieux comme ça! 
Et merci pour la découverte de l'opérateur d'affectation `:=` :)

2023-03-13 10:45 UTC, Allan-CodeWorks commented on get_minimal_version.py
> +        print(f'OpenFisca-Core=={min_version}')
Ah, dommage l'opérateur n'éxiste que depuis python 3.8 :D

2023-03-13 14:41 UTC, Allan-CodeWorks commented on get_minimal_version.py
> +        version = re.search("(Core|France)[\s]*>=[\s]*([\d\.]*)", line)
Petite amélioration pour augmenter la résilience. 
`>m` est entouré de `[\s]*` pour faire en sorte que `OpenFisca-Core >=35.8.0,<36.0` corresponde également.
(ligne tirée du `setup.py` du répôt `openfisca-france`.

2023-03-13 16:24 UTC, Allan-CodeWorks commented on get_minimal_version.py
> +        version = re.search(r'(Core|France)\s*>=\s*([\d\.]*)', line)
Petite amélioration pour augmenter la résilience. 
`>m` est entouré de `[\s]*` pour faire en sorte que `OpenFisca-Core >=35.8.0,<36.0` corresponde également.
(ligne tirée du `setup.py` du répôt `openfisca-france`.

Également une petite retouche de syntaxe qui ajoute `(r'` et supprimes les crochets autour des `\s` pour faire plaisir à flake8. (dans la CI sur le dépôt openfisca-france, et je copie ici pour des raisons de cohérence)

2023-03-20 10:48 UTC, baptou12 requested changes
Pour discussion

2023-03-20 10:48 UTC, baptou12 commented on .github/workflows/workflow.yml
> +        run: | # Script read the setup.py and prints the packages name with minimal version
J'ai l'impression que ce comment aurait plus de sens en description du script `get_minimal_version.py` plutôt qu'ici, t'en pense quoi ?

2023-03-20 10:48 UTC, baptou12 commented on .github/workflows/workflow.yml
> +          key: build-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ github.sha }}-maximal
Une autre solution serai p.e. de mettre ça dans une strategy ? du genre : 
```
    strategy:
      matrix:
        version: [maximal]
```

2023-03-20 10:48 UTC, baptou12 commented on get_minimal_version.py
> +with open('./setup.py') as file:
Ce script pourrait être déplacé dans `.github/` comme les autres script qui ne servent que pour les actions ?

2023-03-21 09:59 UTC, Allan-CodeWorks commented on .github/workflows/workflow.yml
> +          key: build-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ github.sha }}-maximal
Ça te semblerait plus propre? 
D'un côté, utiliser `strategy: matrix` ici est plus jolie à mes yeux mais je me demande si c'est pas plus compliqué à comprendre. 
Dans la situation actuelle on précise au moment utile, que l'on veut la version maximal.
Si on utilise une matrix `maximal` comme proposé, on donne l'information qu'on veut une version `maximale` au début du job mais l'info n'est pas utile à ce moment précis et lorsqu'on lit la ligne qui fait référence à la version utilisée, il faut faire une petite gymnastique pour savoir de quoi on parle.

C'est mon ressenti sur le moment mais doit avoué que la proposition me semble plus élégante!

2023-03-21 10:06 UTC, Allan-CodeWorks commented on get_minimal_version.py
> +with open('./setup.py') as file:
Tout à fait! Merci

2023-03-22 10:36 UTC, Allan-CodeWorks commented on .github/workflows/workflow.yml
> +        version: [minimal, maximal]
@baptou12 
En éditant la PR équivalente sur OpenFisca-France, je me suis dis que le nom `version` n'etait pas totu à fait adapté et j'ai changé  par `openfisca-dependencies`, pour bien montré qu'ont parle des dépendances Openfisca.

Le workflow sur france-local et paris est plus simple mais pour autant je trouve qu'on pourrait renommer `version` également pour mieux exprimer la chose.

Qu'en penses-tu? Est-ce que `openfisca-dependencies` te paraît cohérent?

2023-03-22 10:46 UTC, baptou12 commented on .github/workflows/workflow.yml
> +        version: [minimal, maximal]
Oui carrément ! c'est vrai que on sait pas vraiment ce que ça veut dire ce version ici :-)

2023-03-22 10:47 UTC, baptou12 commented on .github/workflows/workflow.yml
> +        if: matrix.version == 'minimal'
Tu as encore une référence à `.version` ici

2023-03-22 14:52 UTC, baptou12 approved these changes

2023-03-27 14:50 UTC, merged