Transforme l'acces aux conditions des aides de la reforme dynamique en parametres
openfisca/openfisca-france-local pull request #158
Opened 2023-05-05 08:54 UTC by Allan-CodeWorks

2023-05-05 11:06 UTC, Allan-CodeWorks reviewed
Partage de certains questionnements.

2023-06-07 10:10 UTC, Allan-CodeWorks reviewed
Quelques commentaires pour essayer de faciliter la review.

2023-06-07 10:10 UTC, Allan-CodeWorks commented on tests/reforms/aides_jeunes/test_aides_jeunes_reform.yaml
> -    age:  [18, 19]
Toutes les lignes supprimées dans les tests l'on été pour épurer les fichiers (les données ne sont pas nécessaires)

2023-06-08 07:35 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +    def get_conditions(profil):
Pour python 3.10, on attendra un peu.
Par contre, préciser le type même avec la syntaxe `Union` me semble quand même intéressant dans le sens où il permet de donner un sens au `if isinstance(profil, ParameterNode)` juste en dessous, non ? (Tout seul il me semble un peu "sorti de nulle part")

2023-06-08 07:59 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        return data
Je suis d'accord que c'est plus simple avec le return direct.
Pour la vivification, je ne suis pas sûr que ce soit supporté nativement par Python, ou alors je vais avoir besoin d'une petite démo!

2023-06-08 13:42 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        amount = parameters(date.today()).montant
Les aides de type `float` sont les aides qui octroient un montant en euros. 
Une `Variable`(openfisca) de type `float` va donner un résultat en euros en opposition à une aide de type `bool` qui va donner un booléen (On a le droit à l'aide ou pas).

Nous avons donc besoin d'accéder au montant de l'aide uniquement pour les aides de type `float`.
Ce montant étant stocké dans l'arbre des paramètres et nous accédons à un paramètre pour une `Period` précise, ici on utilise la date actuelle car je ne crois pas qu'on fasse des simulation à une date différente du moment actuel.

2023-06-09 07:15 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        ]) > 0
Ici, depcom est obtenu juste au dessus via `depcom = individu.menage('depcom', period)`
en appelant `individu` on obtient un `numpy.array`.

Dans le cas du test faisant appel à `test_condition_communes.yaml`, nous faisons une simulation pour deux individus (donc 2 `depcom`s), on obtient : 
`numpy.array([b'62900', b'77002'])`

Il y a 5 communes éligibles : 
`eligible_depcoms = ['62861', '62863', '62885', '62895', '62900']`

Quand on test l'éligibilité avec 
``` python
[
depcom == eligible_depcom.encode('UTF-8')
for eligible_depcom in eligible_depcoms
]
```

On obtient une liste dont la longueur vaut le nombre de villes éligible. 
Chaque élément est un `numpy.array` de la longueur du nombre de personne dans la simulation (ici 2) :
``` python
[
array([False, False]),
array([False, False]),
array([False, False]),
array([False, False]),
array([ True, False])
]
```

On ne peut pas faire `any()` sur ce tableau, car chaque élément du tableau est un tableau numpy comptant plusieurs éléments.

`sum()` de ce tableau nous donne : 
``` python
[1, 0]
```

On ajoute la comparaison à 0 pour transformer ce tableau en un tableau de booléen : 
``` python
[True, False]
```

Qui indique que la première personne est éligible mais pas la deuxième.

2023-06-09 07:17 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +    return sum(eligibilities) > 0
Même explication que + haut, on opère sur une liste de `numpy.array()`. `any()` ne peut pas marcher.

2023-06-09 13:26 UTC, Shamzic commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        for key in condition.keys():
Ca marche aussi sans le `.keys()`
```suggestion
        for key in condition:
```

2023-06-09 13:26 UTC, Shamzic commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    def generate_simple_parameter(condition: dict) -> Parameter:
Cette méthode pourrait être renommée en quelque chose de plus explicite car ça concerne le cas général des paramètres et les autres cas ne sont finalement que des exceptions. On pourrait utiliser les termes "common" ou "generic", qu'en penses-tu ?

2023-06-09 13:26 UTC, Shamzic commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        profils['profils'][profil['type']] = {date: {'value': True}}
Peut-être que je suis pas habitué avec Python mais ce serait pas plus lisible de sortir ces 3 méthodes de `profils_to_node_data` en les mettant juste avant (par exemple?) car avec l'indentation ça complique la lecture (même si c'est totalement légitime de les laisser là vu qu'elles sont bien utilisées uniquement dans ce contexte)

2023-06-09 13:26 UTC, Shamzic commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +def generate_parameter_in_TBS(parameters, benefit_path: str):
Pourquoi certaines variables sont "typées" et d'autres non comme ici ?

2023-06-09 13:26 UTC, Shamzic commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +    benefit_path: str = f'{test_folder}test_condition_age.yaml'
```benefit_path``` étant utilisé plusieurs fois en dessous, on pourrait imaginer un truc comme ça défini plus haut : 

```python
def benefit_path(test_folder: str):
    return f'{test_folder}test_condition_age.yaml'
    ```

2023-06-09 13:26 UTC, Shamzic commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +    at_instant: ParameterAtInstant = parameters("2023-01-01")
Là aussi cette variable peut être mutualisée

```python
def at_instant(parameters: ParameterNode):
    return parameters("2023-01-01")
```

2023-06-12 07:29 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        #     raise Exception(f'{e.args[0]} in file {path}')
Le KeyError à pour moi beaucoup de sens, car il permet un retour très utile lorsqu'une condition ou un profil n'est pas présent dans la liste connue.
On sait que ça peut arriver et donc j'ai fait en sorte que lorsque qu'on ajoute une aide actuellement non supportée, on reçoive un message clair qui incrimine un fichier précis.

Catcher une erreur générique ne semble pas une super idée d'après mes lectures mais je ne suis pas sûr de ne pas confondre deux choses : lever une exception et couvrir l'erreur en continuant à exécuter le code.

La seule raison pour laquelle j'ai fait cet execpt générique c'est pour avoir une idée du fichier fautif (on ne peut pas avoir accès au nom du fichier plus haut dans la hiérarchie de fonctions)

En écrivant ces mots, je réalise qu'il y a un mécanisme dans Python qui permet de lever une erreur en cascade.
Je vais faire la modification et faire quelques tests.

Je laisse les détails de mon raisonnement pour discussion mais il semblerai que je sois d accord pour laisse uniquement le try/catch générique qui lèvera la même exception que celle qu'il a reçu.

2023-06-12 13:27 UTC, baptou12 requested changes

2023-06-12 13:28 UTC, Allan-CodeWorks commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +def generate_parameter_in_TBS(parameters, benefit_path: str):
En l'occurrence c'est un oubli, merci! :) 

On peut quand même dire quelques mots sur le typage en python : 
Ça s'appelle `type hints`, CAD que ce sont des informations, donc si une fonction  prend en paramètre le `Type A`, préciser un type dans la signature n'empêchera pas du tout qu'on lui envoie un `Type qui n'a rien à voir`. C'est surtout pour la lecture et l'IDE que ça aide.

Donc typer à 100% n'est pas forcément utile, le faire systématiquement n'a pas forcément de sens mais j'aime bien quand c'est homogène! :) 

Sinon, il peut arriver qu'une fonction soit prévue pour accepter différents type et là, on peut faire une union ou laisser sans rien, c'est une discussion un peu p[lus haut pour la fonction `build_profil_evaluator`

2023-06-12 13:45 UTC, Allan-CodeWorks commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +    benefit_path: str = f'{test_folder}test_condition_age.yaml'
Effectivement, merci!

J'ai juste utilisé une feature du framework de test qui s'appelle une `fixture` au lieu d'une fonction classique, mais je ne suis pas sûr de l´intérêt dans notre contexte :D

2023-06-12 13:53 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    date = '2020-01-01'
Merci, est-ce que `openfisca_parameter_date` serait assez parlant pour toi? 

On pourrait ajouter `key` mais je pense que ça pourrait apporter de la confusion pour les persones habituées à openfisca.

2023-06-13 13:40 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        parameter_operator: str = comparison_operators[condition['operator']]
Ah oui merci! C'est corrigé.

Ce qui m'embête avec la manière dont j'ai fait ça c'est que les fonctions `generate_age_parameter`, `generate_quotient_familial_parameter`, `generate_regime_securite_sociale_parameter` et `generate_simple_parameter`
Ne sont pas des fonctions pures...
Je pense que c'est acceptable car on est dans un scope limité mais ça m´embête.

Vous en pensez quoi ?

2023-06-13 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        parameter_operator: str = comparison_operators[condition['operator']]
En fait j'ai revert le changement, je ne peux pas simplement sortir l'assignation au même niveau que `openfisca_parameter_date` car on ne peut pas faire cette assignation dans tous les contextes (ça crash).

On pourrait également créer une fonction qui return ce résultat mais je trouve ça plus clair de répéter ce code que de créer une nouvelle fonction nestée, je trouve ça bien en l'état car les fonctions nestées sont les fonctions relatives aux différents types de conditions et c'est tout.

Je passe peut-être à côté d'une autre solution?

2023-06-13 13:59 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        for key in condition.keys():
Ah oui, merci beaucoup!

2023-06-13 14:44 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    meta_donnees = amount_to_node_data(benefit.get('montant'))
C'est un reliquat, j'ai changé pour `amount_data`.
Merci!

2023-06-13 14:47 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    def generate_simple_parameter(condition: dict) -> Parameter:
Tout a fait d'accord! Merci pour la suggestion, `common`me semble très bien :)

2023-06-13 15:40 UTC, Allan-CodeWorks commented on tests/reforms/aides_jeunes/test_convert_benefit_conditions_to_parameters.py
> +    at_instant: ParameterAtInstant = parameters("2023-01-01")
J'ai essayé de mutualiser avec le framework de test mais n'ai pas réussi.

SI je fais une fonction, je me retrouve avec : 
``` python
at_instant: ParameterAtInstant = at_instant(parameters)
```
à la place de 

``` python
at_instant: ParameterAtInstant = parameters("2023-01-01")
```

Ce qui ne me semble compléxifier la lecture sans gain réel au final :(

2023-06-14 08:22 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                benefit_type: type = bool if benefit['type'] == 'bool' else float
Oui effectivement, il y a les aides qui octroient un montant financier et donc on retourne un nombre comme les aides BAFA.
Il existe aussi les aides qui offrent un service, comment par exemple le `pass'region` de la région AURA, qui est une carte qui permet l'accès à différentes prestations.

Bon, il y a certaines situations un peu plus délicates car on peut trouver des aides comme la `bourse jeunes à l’international` qui retourne un montant mais qui est de type bool. Ça marche parce que le montant est fixe mais ça me pose question.

@Cugniere, est-ce que tu saurais nous éclairer sur ce dernier point ?

2023-06-14 08:42 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                self._create_and_add_parameters(benefit)
Je viens de faire des tests et de push une nouvelle version.
IL ne semble pas nécessaire de venir récupérer le noeud de l'aide en question  pour l'envoyer dans `generate_variable()`.

Par contre, même si les tests passent sans, si on ne fait pas le `add_child()` les paramètres ne seront pas intégrés dans le TBS et donc pas présent dans l'API. Je ne pense pas qu'on veuille ça.

Il faut en discuter de vive voix pour essayer de bien comprendre ce que nous sommes en train de faire.

Je pense que l'avis de @guillett serait pertinent sur cette question.

2023-06-19 12:27 UTC, Shamzic commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    conditions_formated: 'list[dict]' = [
> Est-ce qu'enlever le type t'aide significativement mieux à comprendre ?

Moi je l'aurais pas mis mais c'est trop subjectif, je te laisse faire ton choix 👍

2023-06-21 13:30 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +            print(f'{e.args[0]} while processing file {path}')
Comme le traitement de l'erreur es le même, on pourrait ne pas différentier `KeyError` et `Exception` ici ? Ou sinon le traitement devrait être différent ?

2023-06-21 14:00 UTC, Allan-CodeWorks commented on setup.py
> +        'OpenFisca-Core @ git+http://github.com/openfisca/openfisca-core.git@35.12.0_fix_testrunner_reforme_clone',
Modification supprimée car la branche master est passée sur la version 40+ d'openfisca-core qui intègre le fix

2023-06-21 14:15 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +            print(f'{e.args[0]} while processing file {path}')
La manière dont je vois les choses est la suivante: 
Le `KeyError` sera raise lorsqu'une aide avec **condition** ou un **profil** qu'on ne traite pas encore sera ajoutée.
Dans ce cas précis, on accédera à `profil_table` ou `condition_table` avec une clé inexistante, ce qui va lever une `KeyError` (ligne 303 et 312). À ces endroits, on a  précisé un message qui fait sens.
On veut spécifiquement lever cette erreur pour que le message d'erreur soit le plus clair possible.

Le Exception est là pour les autres cas, qu'on ne peut définir à l'avance mais préciser le fichier d´aide que nous étions en train traiter lors de l'erreur peut vraiment aider au debugging.

La gestion d'erreur est un domaine que je n'ai pas encore beaucoup côtoyé...

Comment gérer ces problématiques?

2023-06-23 08:44 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +            print(f'{e.args[0]} while processing file {path}')
En fait ce que je trouve bizarre c'est à un autre niveau : KeyError est une sous-classe de Exception, et pourtant on les traite de la même façon.

C'est comme si tu disais : 
"Traite les carrés de cette manière et les rectangles de la même manière."
Si on mettait juste :  "Traite les rectangles de cette manière" ça aurai le même comportement.

=> si tu laisse juste le `except Exception` les KeyError iront là aussi.

2023-06-23 13:49 UTC, Shamzic commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        '>': 'strictement_superieur',
Avec ce contexte supplémentaire, je suis bien en phase avec cette dernière suggestion 👍

2023-06-26 08:44 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +        '>': 'strictement_superieur',
Voilà qui est fait, merci beaucoup tes retours! :)

2023-06-26 12:42 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +            print(f'{e.args[0]} while processing file {path}')
Je suppose qu'il y a eu des changements dans la gestion d'erreur dans python entre la 3.7 et la 3.9.

Le problème que j'avais était qu'en relevant une erreur avec un `raise Exception()`, on convertissait l'exception en `Exception` (au lieu de `KeyError` par exemple).
Je pense que cette conversion était un problème car je voulais vraiment lever une `KeyError`.

J'avais mis en place la ligne `Exception` en faisant le trade-off imparfait qu'il était préférable de savoir quel fichier provoquait l'erreur plutôt que de savoir le type d'erreur exacte (qu'on pourrait obtenir dans le processus de debug).

Il possible que je n'ai pas fait assez de tests ou que le comportement de Python ai changé car en investiguant je vois que relever une exception avec une classe parente de l'erreur ne convertit plus l'exception.
J'ai donc opéré les changements suivants : 

```python
        except Exception as e:
            print('\nMore informations about the error:')
            print(f'\x1b[31;20m\n{e.args[0]}\nThis happened while processing file {path}\n\x1b[0m')
            raise
```

(\x1b[31;20m) permet de print en rouge.

Qu'en penses tu ?  @baptou12

2023-07-05 13:03 UTC, baptou12 approved these changes

2023-07-05 16:11 UTC, guillett commented on openfisca_france_local/aides_jeunes_reform.py
> +    elibible_taux = parameters.taux_incapacite
J'avais pas fait attention à cette implémentation, ça me gratte un peu mais c'est pour une PR de refactor dédiée.
https://trello.com/c/avznY1Ez/1368-refactor-la-gestion-du-taux-dincapacit%C3%A9-dans-les-aides-js-et-dans-openfisca-france-local

2023-07-05 16:29 UTC, guillett approved these changes
Franchement bravo !! :tada: une belle itération !
Je n'ai pas encore pris le temps de regarder à quoi ressemble l'arbre des paramètres mais c'est Ok pour moi, on fera d'autres itérations de toutes façons !

2023-07-05 16:29 UTC, guillett commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    data: dict = {'conditions': {}}
Je ne pensais pas que cette imbrication mais je n'ai pas pris le temps de réfléchir à ce que ça implique ou à une alternative _préférable_ (et le pourquoi elle serait préférable) (j'ai aussi tiqué sur la partie get_conditions avec le test sur la structure de l'arbre des paramètres).

2023-07-10 07:21 UTC, Allan-CodeWorks commented on openfisca_france_local/convert_benefit_conditions_to_parameters.py
> +    data: dict = {'conditions': {}}
Je suis preneur d'une discussion sur le sujet pour éclaircir et discuter de ces points :)

2023-07-10 07:22 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +            print('\nMore informations about the error:')
Je n'en connais pas et  n'en vois pas ?

2023-07-10 08:52 UTC, merged