Refacto de réarangement de la réforme aides_jeunes_reform_dynamic
openfisca/openfisca-france-local pull request #160
Opened 2023-05-31 16:07 UTC by Allan-CodeWorks

Dans l'idée d'améliorer la compréhension et la lisibilité du code, voici quelques améliorations: 

- Change l’ordre de certaines méthodes ou fonctions.
- Change le nom l'ordre de certaines méthodes ou fonctions.
- Change le nom de certaines variables.

2023-06-02 08:54 UTC, baptou12 requested changes

2023-06-02 08:54 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +        def _slug_from_filename(benefit_path: str):
J'aime bien l'idée de bouger ces `split`/`replace` dans une sous-méthode, cependant je modifierais deux choses : 
- le nom me semble pas bon, l'argument d'entrée n'est pas vraiment un "filename" mais plutôt un "path" non ? J'aurais mis `_slug_from_path`
- le nom de l'argument est redondant avec la méthode au dessus, je pense qu'on peut l'abstraire un peu pour le renommer simplement `path` par exemple

T'en pense quoi ?

2023-06-02 08:54 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +        liste_fichiers = [
Pas bloquant, mais ici je me dit qu'on rentre dans le cadre d'une partie "technique" du coup j'aurais mis le nom de la variable en anglais plutôt

2023-06-02 12:09 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        def _slug_from_filename(benefit_path: str):
Je pense que ton retour et pertinent, j'étais parti du principe que ce qui nous intéresse dans le path, c'est juste le nom du fichier. et donc que, techniquement, on récupère le nom du fichier pour en faire un slug.

Néanmoins, il est vrai que la donnée en entrée est un path et ton explication m’a semblé très logique.

J'ai déjà push le changement, mais j'ai maintenant un petit doute, la situation d'origine traduit **l'intention**, avec ta suggestion, le nouveau nom est plus proche de **ce que fait réellement** la fonction.

Qu'est-ce qui est le plus intéressant ?

2023-06-02 12:19 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        liste_fichiers = [
Pertinent également, je ne suis plus sûr des directives d'OpenFisca-France concernant la langue à employer pour les variables mais en regardant ce qui est fait je pense également que c'est mieux.

2023-06-06 10:30 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +        def _slug_from_filename(benefit_path: str):
Perso, je trouve que `_slug_from_path` est mieux alors

2023-06-06 12:31 UTC, baptou12 approved these changes

2023-06-06 12:44 UTC, merged