Modelisation aide permis haute saone
openfisca/openfisca-france-local pull request #167
Opened 2023-06-15 11:44 UTC by Valandr

[Source de connaissance](https://www.haute-saone.fr/index.php/nos-e-services/aides-aux-familles/pack-jeunes/)

2023-06-15 15:11 UTC, Allan-CodeWorks requested changes
La structure me semble bien,  il y a quelques détails à revoir pour coller parfaitement au document de référence.

Dans ce même document, on fait référence à une majoration si l'individu est `JSP volontaire`, `gendarme` ou `militaire réserviste`, à voir si c'est possible / pertinent de modéliser ça.

Pareillement, il est spécifié que cette aide n'est pas cumulable avec le FSL (Fonds de Solidarité Logement)

2023-06-15 15:11 UTC, Allan-CodeWorks commented on tests/departements/haute_saone/aide_permis.yaml
> +      2021: ['15050','9700','6000','5000','3000']
Il me semble plus pertinent de tester les bornes limites des différentes échelons du barème:
- à `1201` de QF mensuel (donc 14412 de QF annuel) l'aide **n'est pas** accordée
- à `1200` de QF mensuel (donc 14400 de QF annuel) **100 euros** d'aide sont accordés
- à `1000` de QF mensuel (donc 12000 de QF annuel) **100 euros** d'aide sont accordés
- à `999` de QF mensuel (donc 11988 de QF annuel) **150 euros** d'aide sont accordés
- etc...

2023-06-19 12:32 UTC, Allan-CodeWorks requested changes
Quelques tests supplémentaires seraient les bienvenus
Le cœur du code me semble bon cependant!

2023-06-19 12:32 UTC, Allan-CodeWorks commented on tests/departements/haute_saone/aide_permis.yaml
> +    haute_saone_aide_permis: [0, 100, 150, 250, 400]
Je pense qu'il serait mieux de tester les montants minimums et maximums de `quotient_familial` pour chaque tranche d'aide.
Il faudrait donc un test pour le `QF` *maximal* requis pour toucher **100 euros**, un pour le `QF` *minimal* qui permet de toucher **100 euros**

Pareil pour la tranche qui permet de toucher **150 euros**, 
Pareil pour la tranche qui permet de toucher **250 euros**.

Pour la tranche qui permet de toucher **400 euros**, je pense qu'on peut se permettre de n'écrire qu'un seul test : le `QF` minimal requis pour être éligible à cette tranche.

2023-06-23 15:35 UTC, Shamzic commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
L'encodage ne me semble pas nécessaire pour cette chaîne
```suggestion
        return startswith(menage('depcom', period), 70')
```

2023-06-23 15:35 UTC, Shamzic commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
Apparement on peut aussi optimiser les perfs avec `char.startswith` de numpy (à vérifier) :

```python
  import numpy as np

  ...

  return np.char.startswith(...
```

2023-06-26 15:03 UTC, Allan-CodeWorks commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
> 

Ici, `menage('depcom', period)` retourne un tableau de `bytes` qu'on ne peut comparer directement avec un `string` ou un `number` (enfin, techniquement Python nous laisse le faire mais le comportement n'est pas celui qui nous interesse, ou alors il nous manque quelque chose pour que ça corresponde à ce qu'on veut). 
On utilise `str.encore()` pour convertir le numéro de département en byte et ensuite le comparer.

2023-06-27 07:25 UTC, Allan-CodeWorks requested changes

2023-06-27 07:25 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/departements/haute_saone/aide_permis.yaml
> +  maximum:
Suite aux discussion sur une autre pr, je propose d'utiliser une terminologie qui ne perturbera pas trop les habitudes mais sere moins ambigue:
```suggestion
  maximum_inclusif:
```

2023-06-27 07:25 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/departements/haute_saone/aide_permis.yaml
> +  minimum:
```suggestion
  minimum_inclusif:
```

2023-06-27 10:14 UTC, Allan-CodeWorks commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
> Apparement on peut aussi optimiser les perfs avec `char.startswith` de numpy (à vérifier; ma propositition est issue d'une version plus récente) :
> 
> ```python
>   import numpy as np
> 
>   ...
> 
>   return np.char.startswith(...
> ```

J'ai passé un peu de temps à enquêter sur ton retour, d'après la doc de Numpy, il y a en effet d'autres entrées quand on cherche `startswith` dans le moteur de recherche.

Je suis plutôt confus dans tout ça, de ce que je comprends il ya 4 import différent pour faire la même chose : 
```python
        char.chararray.startswith
        char.startswith
        chararray.startswith
        char.chararray.startswith
```

Tu proposes ` np.char.startswith`, or ça fait référence à la même fonction que celle qu'on utilise déjà (par un jeu d'import)

Les 3 autres : `char.chararray.startswith`, `chararray.startswith`, `char.chararray.startswith` font référence à une autre fonction mais ils la partagent.
Là où ça me dépasse c'est que ce sont des méthodes d'une class `class chararray(ndarray[_ShapeType, _CharDType]):`
surchargée.

Toutes fonctionnent mais je n'arrive pas à voir les différences ou les intérêt. Je ne vois rien dans la doc

Pourrais-tu élaborer stp ? @Shamzic

2023-06-27 10:18 UTC, Allan-CodeWorks requested changes

2023-06-27 10:18 UTC, Allan-CodeWorks commented on setup.py
> +    version="5.1.1",
Ici on ajoute une Variable au Tax and Benefit system (on ajoute une aide) donc on ajoute une fonctionalité, c'est un changement mineur et nom un patch.
```suggestion
    version="5.2.0",
```

2023-06-27 15:05 UTC, Allan-CodeWorks requested changes

2023-06-27 15:05 UTC, Allan-CodeWorks commented on openfisca_france_local/departements/haute_saone/aide_permis.py
> +    reference = 'https://www.haute-saone.fr/index.php/nos-e-services/aides-aux-familles/pack-jeunes/'
Pour la discussion que l'on a eu concernant la date de publication de l'aide, j'ai pu retrouver la date du `29/12/2022` que tu as utilisé dans les paramètres en remontant les liens de la source déjà présente.

Je propose d'ajouter les liens qui permettent de retrouver l'info.
```suggestion
    reference = [
    'https://www.haute-saone.fr/index.php/nos-e-services/aides-aux-familles/pack-jeunes/',
    'https://www.mes-services-publics70.fr/e_services/mpb/',
    ]
```

Pour retrouver la date du 29 décembre 2020 il faut télécharger le PDF en cliquant sur `Arrêté d'homologation du service` sur la source que je propose d'ajouter

2023-06-27 15:05 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/departements/haute_saone/aide_permis.yaml
> +      2023-01-01:
```suggestion
      2020-12-29:
```

2023-06-27 15:05 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/departements/haute_saone/aide_permis.yaml
> +      2023-01-01:
```suggestion
      2020-12-29:
```

2023-06-28 13:02 UTC, merged

2023-06-29 13:44 UTC, Shamzic commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
> Ici, `menage('depcom', period)` retourne un tableau de `bytes` qu'on ne peut comparer directement avec un `string` ou un `number` (enfin, techniquement Python nous laisse le faire mais le comportement n'est pas celui qui nous interesse, ou alors il nous manque quelque chose pour que ça corresponde à ce qu'on veut). On utilise `str.encore()` pour convertir le numéro de département en byte et ensuite le comparer.

Ok! Je pensais que cela renvoyait un `string`, pourrais-tu m'indiquer où est-ce qu'on peut trouver cette information s'il te plaît ?

2023-06-29 13:57 UTC, Shamzic commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
Concernant `startswith`, c'est l'IA qui m'a proposé cela en suggérant une amélioration de performances (d'où ma proposition "à vérifier") et après véirification, c'est effectivement mieux de laisser l'import spécifique plutôt que d'importer tout le module `numpy` comme suggéré au départ.

2023-07-03 09:13 UTC, Allan-CodeWorks commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
> > Ici, `menage('depcom', period)` retourne un tableau de `bytes` qu'on ne peut comparer directement avec un `string` ou un `number` (enfin, techniquement Python nous laisse le faire mais le comportement n'est pas celui qui nous interesse, ou alors il nous manque quelque chose pour que ça corresponde à ce qu'on veut). On utilise `str.encore()` pour convertir le numéro de département en byte et ensuite le comparer.
> 
> Ok! Je pensais que cela renvoyait un `string`, pourrais-tu m'indiquer où est-ce qu'on peut trouver cette information s'il te plaît ?

Alors là... c'est un grand mystère pour moi! Je le sais parce que c'est ce que je vois quand je manipule ces données mais la magie qui explique le pourquoi ce sont des `bytes` est un peu trop dark pour moi. J'ai passé un moment à chercher :/ Désolé @Shamzic

2023-07-03 09:57 UTC, Shamzic commented on openfisca_france_local/departements/haute_saone/eligibilite.py
> +        return startswith(menage('depcom', period), str.encode('70'))
Pas de soucis ^^