Corrige le crash dans le calcul de l'éligibilité à l'aide garde enfant de la région des Hauts de France
openfisca/openfisca-france-local pull request #171
Opened 2023-07-11 13:03 UTC by Allan-CodeWorks

# Description

Une incompatibilité de vecteurs peut survenir dans le cas de familles avec plusieurs membres.
Le tableau des ages et le tableau des montants peuvent prendre des formes incompatibles en fonction du nombre de membre dans une famille;

2023-07-25 14:09 UTC, baptou12 requested changes
Simplement le nom du test. LGTM pour le reste. Test en local avec breakpoint fait aussi

2023-07-26 07:25 UTC, Allan-CodeWorks commented on tests/regions/hauts-de-france/aide_garde_enfant.yml
> +- name: Égibilité et montant blabla a renseigner + tard
Je ne vois pas ce qui te fait dire ça! :grin: 
C'est corrigé, merci :)

2023-08-16 12:29 UTC, Allan-CodeWorks commented on .github/has-functional-changes.sh
> -IGNORE_DIFF_ON="README.md CHANGELOG.md CONTRIBUTING.md Makefile .gitignore .github/*"
J'avais du éditer ce script et ajotuer cette entrée pour que la CI passe dans la PR d'ajotu du fichier de CHANGELOG.md mais le script et maitnenant bloquant, je le remet à l'état d'origine.

2023-08-16 14:52 UTC, baptou12 approved these changes

2023-08-16 15:13 UTC, merged