Ajoute l'aide permis de conduire de region Nouvelle Aquitaine
openfisca/openfisca-france-local pull request #181
Opened 2023-09-11 08:26 UTC by Allan-CodeWorks

2023-09-13 08:48 UTC, Shamzic reviewed
Une suggestion pour améliorer la lisibilité de la méthode `def formula` de l'aide au permis de la nouvelle aquitaine, spliter en petites méthodes pour avoir une  méthode `formula` plus petite afin de voir clairement les calculs requis

2023-09-13 09:01 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +        eligibilite_age = (age >= age_minimum) * (age <= age_maximum)
Merci pour les remarques, voici une nouvelle itération.
Qu'en penses-tu ?

2023-09-13 13:25 UTC, baptou12 commented on openfisca_france_local/parameters/regions/nouvelle_aquitaine/aide_permis.yaml
> +    reference:
Je suis pas sûr de comprendre pourquoi parfois on met reference directement sous la clé racine, parfois dans metadata et par example ici que dans age et pas dans les autres ?

2023-09-13 15:21 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/regions/nouvelle_aquitaine/aide_permis.yaml
> +    reference:
Il est effectivement judicieux de mettre la référence au même niveau que les différents paramètre puisqu'ils sont issus de la même source. Voila qui est fait.

Pour ce qui est de `metadata` ou non, je pense avoir pris une mauvaise habitude depuis un moment que j'ai corrigé il y a peu.
Sur `openfisca-france` on peut voir que la grande majorité des champs `reference` se trouvent dans un champ `metadata`.
C'est probablement le comportement à retenir pour la suite.

2023-09-14 08:57 UTC, baptou12 requested changes, later dismissed
J'ai des questions sur `eligibilite_profile` si on peut faire ça en synchro

2023-09-14 08:57 UTC, baptou12 commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +        est_lyceen = individu('scolarite', period) == TypesScolarite.lycee
Pour le même type de calcul tu assigne la variable `activité` vs pas la variable scolarité, je propose d'homogénéiser : 
```suggestion
        est_chomeur = individu('activite', period) == TypesActivite.chomeur
        est_lyceen = individu('scolarite', period) == TypesScolarite.lycee
```

2023-09-14 08:57 UTC, baptou12 commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +    def formula(individu, period):
Chaud pour en discuter, car je comprend pas le lien entre cette formule et ce que je vois sur le site : mais je doute de comment j'interprète l'aide

2023-09-15 09:19 UTC, Allan-CodeWorks commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +        est_lyceen = individu('scolarite', period) == TypesScolarite.lycee
Très juste, bien vu et merci :)

2023-09-15 13:22 UTC, Allan-CodeWorks commented
Labels + documentation sur la modélisation ajoutées.

2023-09-18 09:46 UTC, Shamzic requested changes

2023-09-18 09:46 UTC, Shamzic commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +    label = "Éligibilité d'age de l'aide au permis de la région Nouvelle-Aquitaine"
```suggestion
    label = "Éligibilité d'âge de l'aide au permis de la région Nouvelle-Aquitaine"
```

2023-09-18 09:46 UTC, Shamzic commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +    Sont modélisées en fonction des profils susceptibles d'être intéressés lors d'une simulation avec Aides-Jeunes.
```suggestion
    Les conditions décrites dans le paragraphe `Diplômé de la filière professionnelle ou agricole en insertion professionnelle` sont modélisées en fonction des profils susceptibles d'être intéressés lors d'une simulation avec Aides-Jeunes.
```

2023-09-18 09:46 UTC, Shamzic commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +    De plus, les profils décris dans les paragraphes suivants ne sont pas modélisés :
```suggestion
    De plus, les profils décrits dans les paragraphes suivants ne sont pas modélisés :
```

2023-09-18 12:42 UTC, Shamzic commented on openfisca_france_local/regions/nouvelle-aquitaine/aide_permis.py
> +        eligibilite_age = (age >= age_minimum) * (age <= age_maximum)
C'est good!

2023-09-18 13:03 UTC, Shamzic approved these changes

2023-09-18 13:14 UTC, merged