feat: ajout de l'aide au permis des yvelines
openfisca/openfisca-france-local pull request #186
Opened 2023-10-26 13:15 UTC by baptou12

Ticket: https://trello.com/c/Qf8uitF6/1469-ajouter-laide-au-permis-de-conduire-du-d%C3%A9partement-des-yvelines
Instructions : https://www.78-92.fr/annuaire/aides-et-services/detail/laide-au-financement-du-permis-de-conduire

2023-11-22 11:04 UTC, Shamzic requested changes, later dismissed
Une remarque sur le nommage des variables et quelques questions/doutes sur les specs.

Y a aussi un problème de numéro de version car je crois que ça date un peu (me suis permis de rebase)

2023-11-22 11:04 UTC, Shamzic commented on openfisca_france_local/departements/yvelines/aide_permis.py
> +        rbg = individu.foyer_fiscal('rbg', period.n_2)
J'ai un doute ici : "Le revenu global de la famille ou du jeune figurant sur l’avis d’imposition de l’année précédant la demande". Est-ce que tu t'es trompé sur l'année n-2 et c'est n-1 ou bien c'est une demande pour l'année prochaine et donc il faut prendre l'année n-2 à cause de cela ?

2023-11-22 16:52 UTC, baptou12 commented on openfisca_france_local/parameters/departements/yvelines/aide_permis.yml
> +      2010-01-01:
Si en 2023 ça fonctionne, mais pas en 2009 cf le lien de l'aide

2023-11-27 13:27 UTC, Allan-CodeWorks commented on openfisca_france_local/parameters/departements/yvelines/aide_permis.yml
> +      2010-01-01:
(c'est la date de l'entrée en vigueur du dispositif)

2023-11-27 13:29 UTC, Allan-CodeWorks commented on openfisca_france_local/departements/yvelines/aide_permis.py
> +        rbg = individu.foyer_fiscal('rbg', period.n_2)
Je pense comme toi que c'est n-1 qu'il faut prendre au vu des infos relayées en source, j'ai fais la modif

2023-11-28 15:30 UTC, baptou12 reviewed
Ça me semble good et même mieux (je peux pas approve). Mais toujours la gestion de rgb qui va falloir réglé dans aides-jeunes

2023-12-04 08:46 UTC, Allan-CodeWorks approved these changes
Travail conjoint et suite au commentaire de Baptiste je merge

2023-12-04 08:48 UTC, merged