Ajout du dispositif Revenu Solidarite Jeune de la métropole de Lyon
openfisca/openfisca-france-local pull request #189
Opened 2023-11-15 11:05 UTC by Allan-CodeWorks

### Added

- Ajout du dispositif Revenu Solidarite Jeune de la métropole de Lyon

2023-11-22 10:45 UTC, Shamzic requested changes
Une remarque pour le nom du fichier du rsj, les autres remarques ne sont des suggestions optionnelles. 

Fonctionnel en local !

2023-11-22 10:45 UTC, Shamzic commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
Le nom du fichier a une petite coquille `eligibilie`. 

Je remarque aussi que les autres fichiers du répo concernant les éligibilités résidentielles sont nommés "eligibilite.py", peut-être que ce serait mieux d'utiliser ce nom ici aussi pour uniformiser ?

2023-11-22 10:45 UTC, Shamzic commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
> +        return menage("menage_dans_epci_siren_200046977", period)
Ca pourrait être bien de tester `menage_dans_epci_siren_200046977` un peu à la manière de ce [test ](https://github.com/openfisca/openfisca-france-local/blob/6d6af96da2bf8bf5ae36ae457faa095928da5380/tests/test_epci_reform.yaml)

2023-11-22 10:45 UTC, Shamzic commented on openfisca_france_local/metropoles/lyon/revenu_solidaire_jeune.py
> +        eligibilite_prestations = rsa + aah + aeeh + contrat_engagement_jeune == 0
Intéressant, les additions ont a la priorité sur l'opération de comparaison 👍 
(Pas forcément nécessaire si on connait la règle du coup mais j'aurais ajouté des parenthèses pour la lisibilité)

2023-11-22 15:47 UTC, Allan-CodeWorks commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
Ah oui effectivement. bien vu!

2023-11-22 15:59 UTC, Allan-CodeWorks commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
> +        return menage("menage_dans_epci_siren_200046977", period)
Je suis un peu mitigé, le test en question test la `epci_test_factory`. On peut effectivement lui reprocher de ne vérifier que cela fonctionne que pour une seule `EPCI`.
Ici on ne fait qu'utiliser cette réforme, tester cette formule revient à tester la  réforme `epci_test_factory` et ce n'est pas vraiment le sujet ici.

Je trouve que la réforme est effectivement un peu légèrement testée mais je n'ai pas pris le temps de voir comment tester mieux et je ne suis pas convaincu par la valeur de dupliquer un test existant en changeant juste la valeur.

Je propose de créer un ticket pour investiguer la question en dehors de cette PR, qu'en penses-tu ?

2023-11-22 16:22 UTC, Allan-CodeWorks commented on openfisca_france_local/metropoles/lyon/revenu_solidaire_jeune.py
> +        eligibilite_prestations = rsa + aah + aeeh + contrat_engagement_jeune == 0
C"est une bonne remarque, j'ai préféré mettre toute la partir "addition" dans une variable `prestations_incompatibles` pour expliciter au max!

2023-11-24 13:59 UTC, Shamzic commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
> +        return menage("menage_dans_epci_siren_200046977", period)
> Je propose de créer un ticket pour investiguer la question en dehors de cette PR, qu'en penses-tu ?

Oui bonne idée. J'avais pas compris d'où ça provenait mais j'ai trouvé, ça vient d'ici : [is_epci_eligible](https://github.com/openfisca/openfisca-france-local/blob/dc26a7704423798070667eb37004c942582b897a/openfisca_france_local/aides_jeunes_reform.py#L181) et ça vaudrait effectivement le coup d'ajouter un petit test sur cette méthode dans une autre PR :)

2023-11-24 14:01 UTC, Shamzic commented on openfisca_france_local/metropoles/lyon/eligibilie_residentielle.py
> +        return menage("menage_dans_epci_siren_200046977", period)
> Je propose de créer un ticket pour investiguer la question en dehors de cette PR, qu'en penses-tu ?

Oui bonne idée. J'avais pas compris d'où ça provenait lors de ma review, ça vaudrait effectivement le coup d'ajouter un petit test sur cette méthode dans une autre PR :)

2023-11-24 14:02 UTC, Shamzic approved these changes

2023-11-27 09:17 UTC, merged