Corrige warning `deprecated path()` dans la réforme `epci_test_factory`
openfisca/openfisca-france-local pull request #190
Opened 2023-11-15 16:27 UTC by Allan-CodeWorks

## Fixed

- Corrige le warning lié à l'utilisation de `ressource.path()` dans la réforme `epci_test_factory`

2023-11-16 09:21 UTC, baptou12 commented on setup.py
> -            'xlrd == 1.2.0',
Je me souvient plus du status de cette dépendance. Pourquoi on peut l'enlever déjà ?

2023-11-20 08:19 UTC, Allan-CodeWorks commented on setup.py
> -            'xlrd == 1.2.0',
Je tire des conclusions indirecte: 
- `Xlrd` m'a été présentée en tant que dépendance pour lire les fichiers excels de la réforme `epci_test_factory` qui lit le fichier `epcicom2020.xlsx` pour intégrer les epci dans openfisca
- La dépendance n'a pas été touchée son ajout initial pour la réforme
- Aucun autre fichier `xlsx` n'est présente dans le dépôt

Dans mon investigation pour supprimer le warning je comprends que:
- `pandas.read_excel` fonctionne avec un `engine` pour ouvrir les fichiers
- Lors de la dernière mise à niveau de `Pandas`, il m'a demandé une nouvelle dépendance : `openpxl`
- `openpxl` est devenue le moteur par défaut de `pandas.read_excel`
- `xlrd 1.2.0` est pas sécure, et les versions d'après ne lisent plus les fichiers `xlsx`

Donc, en résumé, `pandas_excel` utilisaient `xlrd` pour ouvrir le fichier mais maintenant on utilise `openpxl` à la place et `xlrd == 1.2.0` a une faille de sécu.

2023-11-20 09:20 UTC, baptou12 commented on setup.py
> -            'xlrd == 1.2.0',
Ok merci ! oui c'est bien ce que je constate apr§es quelques recherche dans le repos

2023-11-20 09:26 UTC, baptou12 requested changes
Au moins on peut en discuter

2023-11-20 09:26 UTC, baptou12 commented on openfisca_france_local/epci_test_factory.py
> +        with open('openfisca_france_local/epcicom2020.xlsx', 'rb') as file:
J'ai l'impression qu'on peut simplifier encore plus en ne gérant pas du tout l'aspect fichier de cette méthode car panda peut prendre un lien aussi : 
```
class epci_reform(reforms.Reform):
    def apply(self):
        raw = pd.read_excel('openfisca_france_local/epcicom2020.xlsx')
        raw.insee = raw.insee.astype('|S5')
        df = raw[['siren', 'insee', 'raison_sociale']].groupby('siren')

        for siren in df.groups:
            self.add_variable(epci_test_factory(df, siren))
```

2023-11-20 13:31 UTC, Allan-CodeWorks commented on openfisca_france_local/epci_test_factory.py
> +        with open('openfisca_france_local/epcicom2020.xlsx', 'rb') as file:
la ligne qui commence par `width` est un `context manager`, dont l'une des fonctions est de gérer l'ouverture et la fermeture des fichiers.

Il est effectivement possible de ne pas l'utiliser, le problème c'est que pandas ne fermera pas le fichier automatiquement.
Dans d'autres contextes, je sais que si on ne fait que lire le fichier ce n'est pas grave mais je ne suis pas sûr que ce soit identique ici et je ne pense pas que ce soit une bonne pratique non plus.

J'imagine qu'on pourrait fermer le fichier avec une ligne de code mais on perd le bénéfice de la simplification voulue il me semble.
Le `with` statement semble être la norme lorsqu'on manipule des fichiers à l'heure actuelle.

2023-11-20 14:06 UTC, baptou12 commented on openfisca_france_local/epci_test_factory.py
> +        with open('openfisca_france_local/epcicom2020.xlsx', 'rb') as file:
Ah, je me disais que panda (comme il donne pas accès au fichier ouvert) se chargeait lui même d'ouvrir, charger la data dans le dataframe puis fermer le fichier dans ce cas là. J'ai vérifier eton dirais bien qu'il close le fichier : https://github.com/pandas-dev/pandas/blob/9aa176687c04227af1c645712ea73296861858a3/pandas/io/excel/_base.py#L549C23-L549C23

2023-11-21 09:29 UTC, Allan-CodeWorks commented on openfisca_france_local/epci_test_factory.py
> +        with open('openfisca_france_local/epcicom2020.xlsx', 'rb') as file:
Je vois ce que tu veux dire, il m'est difficile de vérifier.
Dans le code que tu donnes (qui est aussi présent sur la branche master), ça close dans le cas ou `should_close` est à true ce qui semble être le cas si on passe un type `str` à `read_excel` comem nous le faisons.

J'ai essayé de réouvrir le fichier à la fin du code pour voir si ça déclenchait une erreur mais ce n'est pas le cas.
Je pense donc que tu as raison, j'ai enlevé le context-manager!

2023-11-21 09:34 UTC, baptou12 approved these changes
LGTM

2023-11-21 13:04 UTC, merged