Reform dynamique : ajoute la gestion de la condition `attached_to_institution`
openfisca/openfisca-france-local pull request #191
Opened 2023-11-21 13:56 UTC by Allan-CodeWorks

# Description

La condition `attached_to_instititution` n'as pas été développée jusqu'a maintenant car elle n'est pas explicitée dans le fichier yaml d'une aide.
Cette condition est une condition géographique dont le périmètre est régi par l'institution en question.
Les aides avec cette condition ont un champ `institution` dans lequel réside une chaine de caractères qui correspond a nom d'un fichier dans un autre répertoire sans leur extension `.yml` (pas compatible avec `.yaml` pour le moment)

Cette particularité technique implique que la condition ne peut pas être traitée comme les autres car il faudrait intégrer toutes les institutions dans openfisca, ce qui ne semble pas souhaitable.

Cette PR propose donc d'agir avant l'importation des aides dans le tax and benefit system, juste après avoir lu les fichiers d'aides et les avoir transformés en `dict`, on :
- supprime la condition `attached_to_institution` des `conditions_generales`
- lit le fichier de l'institution correspondante grâce au champ `institution`
- ajoute une condition géographique équivalente aux informations du fichier `institution` dans les conditions générales

### Modifié en même temps : 

Dans le `boy scout spirit` je me suis dit qu'il était ok de faire quelques changements : 
- simplification de la gestion des path par défaut
- changement du type d'erreur remontée en cas de condition ou profil inconnu, on passe de `KeyError` à `NotImplementedError`

### Added

- Ajoute la gestion de la condition `attaches_to_institution`

2023-11-22 15:48 UTC, baptou12 requested changes
Je te l'ai review comme si c'était good commit par commit, si tu veux les changer. 

Sinon on peut ignorer.

2023-11-22 15:48 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_institution_eligible(individu: Population, period: Period, parameters: ParameterNodeAtInstant) -> np.array:
Je pense qu'on peut enlever ça de ce commit, c'était un test c'est bien ça ? (cf `individus_taux_incapacite` pour depcom ?)

2023-11-22 15:48 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
>  benefit_path = 'test_data/benefits'
On pourrait les préfixer `default_` t'en pense quoi ?

2023-11-22 15:48 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                conditions_generales = [condition for condition
ça peut faire long mais dans les fait c'est un `others_condition_generales` ou bien un `condition_generales_without_institution` non ?

2023-11-23 08:21 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_institution_eligible(individu: Population, period: Period, parameters: ParameterNodeAtInstant) -> np.array:
C'est une relique de mes expérimentations initiales, j'ai mal du rebase mes commits, ce chagement a du être absorbé dans un commit ultérieur, la ligne n'est pas présente à l´état final

2023-11-23 08:25 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
>  benefit_path = 'test_data/benefits'
Ça me parait être une très bonne remarque, ça explicite bien!

2023-11-23 09:06 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                benefit: dict = self._extract_file_content(benefit_path, self.institutions_folder_path)
Hmm, c'est un balbutiement de ma part :
Je suis tiraillé entre faire des fonctions pures et profiter du mécanisme de la Class.

Je vois effectivement peu de risque à ne pas faire une fonction pure dans ce cas-là mais je me disais que c'était une bonne habitude :/

2023-11-23 09:21 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                conditions_generales = [condition for condition
Tout à fait, je ne suis pas favorable a `others_condition_generales`, je préfère `condition_generales_without_institution` mais ajouté `attached`

2023-11-23 09:33 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                benefit: dict = self._extract_file_content(benefit_path, self.institutions_folder_path)
On va dire que si c'est un argument c'est que ça pourrait être changé : sur une même instance on pourrait utiliser _extract_file_content avec différents `institutions_folder_path`.

Comme on a pas de cas d'utilisation (du moins pour le moment) autant enlever cette possibilité qui pourrait être mal interprétée par d'autres devs

2023-11-23 09:36 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_institution_eligible(individu: Population, period: Period, parameters: ParameterNodeAtInstant) -> np.array:
Je devrais pouvoir m'en sortir seul, j'avais prévu de laisser comme ça mais je vais prendre ça pour un défis :P

2023-11-23 09:37 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                benefit: dict = self._extract_file_content(benefit_path, self.institutions_folder_path)
Me voila convaincu, merci d'avoir pris le temps de développer!

2023-11-23 09:39 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +        file: dict = yaml.safe_load(open(path))
Ah oui bien vu, ça date de mes essais du début, je pensais parser toutes les institutions.... Je vais renommer la fonction également!

2023-11-23 09:40 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +def is_institution_eligible(individu: Population, period: Period, parameters: ParameterNodeAtInstant) -> np.array:
Pour info, au cas où, tu n'es pas obligé de t'embêter à les rebase comme la PR est relativement petite. Tu peux reset les commits et les recréé mais a partir de la versions finale du code.

2023-11-23 09:45 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = 'epcis'
Je ne suis pas sûr de comprendre le commentaire, j'ai l'impression que tu confirmes que la condition marche bien?

2023-11-23 09:48 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +            file: dict = yaml.safe_load(file)
HA! Alors oui ça marche, oui j'override file mais je ne l'ai pas fait consciement, si seulement j'avais des const...

2023-11-23 11:07 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = f"{institution_type}s"
Oui. La variable openfisca `region` est basée sur le depcom. J'ai fait le test dans le doute et çá fonctionne bien!

2023-11-23 12:23 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = f"{institution_type}s"
Ok, mais ça me parait bizarre car les region de base dans aides-jeunes (JS) sont de cette forme : https://github.com/betagouv/aides-jeunes/blob/ed7ad3635dd2543e9605ab057bb410c5e54443f6/data/benefits/javascript/ile-de-france-aide-au-merite.yml#L16-L18 Donc c'est pas un depcom si ?

2023-11-23 12:32 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = 'epcis'
yes :-)

2023-11-23 12:59 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                    conditions_generales_without_attached_institution = [
On est d'ac que c'est équivalent à ça ? 
```
conditions_generales_without_attached_institution.push({'type': condition_type, 'values': condition_value})
```
C'est p.e. plus simple non ?

2023-11-23 13:01 UTC, baptou12 requested changes
Top juste la question sur les regions et une proposition de simplification de code

2023-11-23 13:52 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = f"{institution_type}s"
En fait l'INSEE à un code qui permet de désigner les zones géographiques de la france.
Les depcom sont les codes qui désignent les _communes_ mais on a aussi des code pour les _départements_, les _régions_ et même des _zones_. (cf [wikipedia](https://fr.wikipedia.org/wiki/Codes_g%C3%A9ographiques_de_la_France)).

Il éxiste dans openfisca [la variable `region`](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/caracteristiques_socio_demographiques/logement.py#L71) qui fait la correspondance entre le code insee de la commune et le code insee de la région.

2023-11-23 13:58 UTC, Allan-CodeWorks commented on openfisca_france_local/aides_jeunes_reform.py
> +                    conditions_generales_without_attached_institution = [
Ah oui pour le coup j'ai poussé le bouchon du fonctionel un peu loin là :D

2023-11-23 14:21 UTC, baptou12 commented on openfisca_france_local/aides_jeunes_reform.py
> +                        condition_type = f"{institution_type}s"
Top merci c'était ce dernier point que je n'avais pas en tête.

2023-11-23 14:35 UTC, baptou12 approved these changes
LGTM, merci pour les rebases

2023-11-27 09:04 UTC, merged