Ajoute un test de présence pour le fichier epcicom2020.xlsx
openfisca/openfisca-france-local pull request #198
Opened 2023-12-15 13:43 UTC by Shamzic

2023-12-18 10:57 UTC, Allan-CodeWorks requested changes
En tant que tel, je crois que le test n'apporte pas de valeur car si le fichier en question n 'est pas présent, le test de la réforme EPCI ne passera pas :/

2023-12-18 10:57 UTC, Allan-CodeWorks commented on openfisca_france_local/scripts/openfisca_local_test
Je crois que la problématique évoquée dans le ticket est de s'assurer que le chemin utilisé pour charger la réforme sera valable quand le module est utilisé.
Il ne s'agit pas de tester la présence du fichier mais la validité du chemin.

À la base, j'ai voulu supprimer des avertissements de dépréciations dans la [réforme EPCI](https://github.com/openfisca/openfisca-france-local/blob/master/openfisca_france_local/epci_test_factory.py) sauf que j'ai remplacé la fonction dépréciée `resources.path('openfisca_france_local', 'epcicom2020.xlsx')` par une URI en dur `pd.read_excel('openfisca_france_local/epcicom2020.xlsx')`

Le problème c'est que le rôle de la méthode `path()` (remplacée actuellement par `files('openfisca_france_local').joinpath('epcicom2020.xlsx')`) est de lié un _package_ à un chemin.

Autrement dit, quand on appelle openfisca dans le dépôt externe, le fichier `epcicom2020.xlsx` n'est pas présent dans l'arborescence du projet en question. Ce qu'on fait ici c'est de dire "va chercher le fichier `epcicom2020.xlsx` dans le dossier du **package** `openfisca_france_local`"

Le test à écrire est donc de vérifier que l'URI utilisée lorsque `openfisca_france_local` est utilisée en tant de que dépendance ne dépend pas de l'arborescence du projet en question...

2024-01-02 14:31 UTC, Allan-CodeWorks commented
Il semblerait que j'ai trouvé un moyen de tester : 
par défaut le dossier d'exécution des tests est la racine du dépôt.
En changeant le chemin d'exécution avec `chdir` vers un dossier temporaire généré par pytest dans /tmp.

Pour vérifier que ça marche bien j'ai pris l'ancienne version de la reforme qui ne marchait pas et on voit bien que le test échoue avec cette version mais pas avec la nouvelle.

2024-01-02 16:36 UTC, Shamzic commented
Je suis à l'origine de la PR mais ok pour la modif avec le test du chemin temporaire en python @Allan-CodeWorks

2024-01-08 13:03 UTC, Allan-CodeWorks commented
En attente de régler les problèmes de déploiement sur Pypi.

2024-01-18 10:55 UTC, Allan-CodeWorks approved these changes

2024-01-18 10:55 UTC, merged