MAJ OF local - Loire Atlantique aide à la mobilité
openfisca/openfisca-france-local pull request #213
Opened 2024-09-19 15:18 UTC by jenovateurs

Liée à https://github.com/betagouv/aides-jeunes/issues/4610

2024-09-20 09:37 UTC, Shamzic reviewed
J'ai fait fonctionné les tests de cette manière

2024-09-20 09:37 UTC, Shamzic commented on tests/departements/loire_atlantique/aide_mobilite.yml
> +    loire_atlantique_aide_mobilite_permis_b: [750, 750, 0, 0]
```suggestion
    loire_atlantique_aide_mobilite_permis_am: [150, 0, 0, 0]
    loire_atlantique_aide_mobilite_permis_b: [750, 0, 0, 0]
```

2024-09-20 09:37 UTC, Shamzic commented on tests/departements/loire_atlantique/aide_mobilite.yml
> +    loire_atlantique_aide_mobilite_permis_b:  [500, 500, 0, 0]
```suggestion
    loire_atlantique_aide_mobilite_permis_am: [100, 0, 0, 0]
    loire_atlantique_aide_mobilite_permis_b:  [500, 0, 0, 0]
```

2024-09-20 09:37 UTC, Shamzic commented on openfisca_france_local/parameters/departements/loire_atlantique/aide_mobilite.yml
> +          value: 500
```suggestion
montant_en_fonction_du_quotient_familial_permis_am:
  description: Montant obtenu pour l'aide au permis moto de conduire.
  metadata:
    type: single_amount
  brackets:
    - threshold:
        2018-01-01:
          value: 0
        2022-01-01:
          value: 0
      amount:
        2018-01-01:
          value: 150
        2022-01-01:
          value: 100
    - threshold:
        2018-01-01:
          value: 801
        2022-01-01:
          value: 601
      amount:
        2018-01-01:
          value: 0
        2022-01-01:
          value: 0
montant_en_fonction_du_quotient_familial_permis_b:
  description: Montant obtenu pour l'aide au permis B de conduire.
  metadata:
    type: single_amount
  brackets:
    - threshold:
        2018-01-01:
          value: 0
        2022-01-01:
          value: 0
      amount:
        2018-01-01:
          value: 750
        2022-01-01:
          value: 500
    - threshold:
        2018-01-01:
          value: 801
        2022-01-01:
          value: 601
      amount:
        2018-01-01:
          value: 0
        2022-01-01:
          value: 0
```

2024-09-20 13:01 UTC, Shamzic requested changes
Manque plus qu'une petite mise à jour du changelog et du numéro de version dans le setup.py, et ce sera bon (:

2024-09-20 13:01 UTC, Shamzic commented on openfisca_france_local/parameters/departements/loire_atlantique/aide_mobilite.yml
> +        href: https://www.loire-atlantique.fr/upload/docs/binary/2018-12/3-reglement_permis_2019_v24-08-2018.pdf
Dommage, les liens sont morts

2024-09-20 13:05 UTC, jenovateurs commented on openfisca_france_local/parameters/departements/loire_atlantique/aide_mobilite.yml
> +        href: https://www.loire-atlantique.fr/upload/docs/binary/2018-12/3-reglement_permis_2019_v24-08-2018.pdf
Le problème est assez commun à bon nombre d'aides. Pour moi, il est possible d'aller fouiller dans le cache de Google ou sur WebArchive. Quant à stocker les documents sur GitHub, je pense que ce n’est pas le bon outil pour. Qu'en penses-tu ?

2024-09-23 12:49 UTC, Shamzic approved these changes

2024-09-23 12:55 UTC, merged