Ajoute l'aide "Pass Jeune 54"
openfisca/openfisca-france-local pull request #215
Opened 2024-09-20 15:14 UTC by Shamzic

2024-09-23 06:38 UTC, jenovateurs requested changes
Merci pour l'ajout, juste quelques petits détails à mettre à jour.

2024-09-23 06:38 UTC, jenovateurs commented on setup.py
> +    version='6.13.0',
Juste pour comprendre le système de versionning, pourquoi passer à la v x.13.x ?

2024-09-23 06:38 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        return rfr / nbptr / 12
J'ai aussi vu du rfr / 12 / nbptr que je trouve plus logique à lire mais en mode tu repasse sur une valeur mensuelle et tu divises par le nombre de part. Mais j'ai pas l'impression de voir une solution tranché dans le code.

2024-09-23 06:38 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        print('min et max ************* ', age_minimum, age_maximum)
```suggestion

```
A supprimer

2024-09-23 06:38 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        "Règlement relatif au Pass Jeune 54 du département Meurthe-et-Moselle",
En titre ?

2024-09-23 06:38 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        quotient_familial = individu('quotient_familial_pass_jeune_54', period)
Dommage qu'on ne puisse pas utiliser une fonction générique à tous en mode quotient_familial.

2024-09-23 08:27 UTC, Shamzic commented on setup.py
> +    version='6.13.0',
Openfisca est en [SemVer Semantic Versioning](https://semver.org/lang/fr/). L'ajout d'un dispositif rentre dans le cadre d'une version mineure, et [historiquement on a fait ainsi avec Allan](https://github.com/openfisca/openfisca-france-local/pull/189).

2024-09-23 08:30 UTC, jenovateurs commented on setup.py
> +    version='6.13.0',
Merci pour l'info, je n'avais pas cet historique :-).

2024-09-23 08:30 UTC, Shamzic commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        return rfr / nbptr / 12
C'est un morceau de code qu'il serait peut-être bien de mutualiser car il se répète à plusieurs endroit (dans certaines aides au permis par exemple)

2024-09-23 08:32 UTC, Shamzic commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        "Règlement relatif au Pass Jeune 54 du département Meurthe-et-Moselle",
Je n'ai pas compris ?

2024-09-23 08:39 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        "Règlement relatif au Pass Jeune 54 du département Meurthe-et-Moselle",
Pour moi :     
```
reference = [
        "Règlement relatif au Pass Jeune 54 du département Meurthe-et-Moselle",
```

Reference ne doit contenir que des liens et tu as mis un titre ici, utilisable avec la propriété title non ?

2024-09-23 08:39 UTC, jenovateurs commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        return rfr / nbptr / 12
Un nouveau ticket ?

2024-09-23 09:04 UTC, Shamzic commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        "Règlement relatif au Pass Jeune 54 du département Meurthe-et-Moselle",
Oui effectivement, j'ai repris la structure d'une aide existante

2024-09-23 09:24 UTC, Shamzic commented on openfisca_france_local/departements/meurthe_et_moselle/pass_jeune_54.py
> +        return rfr / nbptr / 12
Yes [c'est ajouté](https://github.com/orgs/betagouv/projects/42/views/1?pane=issue&itemId=80701642)

2024-09-23 12:33 UTC, jenovateurs approved these changes
Tout est bon pour moi, merci @Shamzic

2024-09-24 11:08 UTC, Shamzic commented
Rebase suite au dernier merge sur master: màj du numéro de version dans le changelog et le setup.py

2024-09-25 07:55 UTC, merged