Mise à jour des communes associées à la mutuelle communale de la métropole de Montpellier
openfisca/openfisca-france-local pull request #221
Opened 2024-12-27 14:25 UTC by jenovateurs

https://encommun.montpellier.fr/articles/2024-12-19-lagence-de-la-mutuelle-communale-de-montpellier-est-ouverte

2025-01-01 17:40 UTC, Shamzic requested changes

2025-01-01 17:40 UTC, Shamzic commented on openfisca_france_local/communes/montpellier/eligibilite_metropole_mutuelle.py
> +        ])
Ici c'est une éligibilité sur un choix de communes spécifique à la mutuelle communale et tu l'as bien précisé dans le nom du fichier. Donc pour appuyer la logique, je propose d'expliciter le nom de cette variable (ex: `montpellier_mutuelle_eligibilite_residence`) et de préciser l'info aussi dans le label

2025-01-01 17:40 UTC, Shamzic commented on openfisca_france_local/communes/montpellier/eligibilite_metropole_mutuelle.py
> +            b'34077',  # Clapier
```suggestion
            b'34077',  # Clapiers
```

2025-01-01 17:40 UTC, Shamzic commented on openfisca_france_local/communes/montpellier/eligibilite_metropole_mutuelle.py
> +        return sum(menage('depcom', period) == code for code in [
Comme tu as défini `value_type = bool` ce serait plus logique d'utiliser `any()` retournant un booléen à la place de `sum()` qui retourne un entier:

```suggestion
        return any(menage('depcom', period) == code for code in [
```

2025-01-02 10:23 UTC, jenovateurs commented
Merci pour tes suggestions d'amélioration @Shamzic. Par contre, pour le remplacement de sum par any, j'obtiens une erreur de mémoire. Je viens d'ajouter les modifs et attends les résultats de tests.

2025-01-02 13:16 UTC, Shamzic commented
Tu peux tester localement avec la commande suivante : 

> openfisca_local_test tests/communes/montpellier/montpellier_mutuelle_communale.yml

Pour l'utilisation de sum, j'ai trouvé un exemple qui fonctionne ici : https://github.com/openfisca/openfisca-france-local/blob/ded15d243662f290eaf0bfd5e147fb9512e809be/openfisca_france_local/aides_jeunes_reform.py#L60-L69

2025-01-02 13:44 UTC, Shamzic approved these changes

2025-01-02 13:49 UTC, merged