[WIP] Ajout gestion aides menageres
openfisca/openfisca-france-local pull request #69
Opened 2020-11-13 16:24 UTC by CecileIAEGI

Ajout des aides menageres pour les personnes agees et en situation de handicap

2020-11-26 20:37 UTC, sandcha requested changes
Bravo @CecileIAEGI Pour cette première PR 🙌 

Les retours de cette revue concernent essentiellement : 
* une correction des opérateurs
* une interrogation sur la composition des bases de ressources

Complément à venir sur les tests après la mise à jour des opérateurs.
Les PR suivantes auront, par effet de bord, moins de commentaires ^^

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        individu_resources = sum([individu(resource, period.last_month) for resource in individual_resource_names])
> À vérifier après prise en compte des premières remarques : la liste est-elle nécessaire dans le sum ? 🤔

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +aide_menagere:
Créer un répertoire `eure_et_loir` et y ajouter un fichier YAML dédié sur le même modèle que le découpage en fichiers Python des variables ? Ceci nécessitera le renommage des appels aux paramètre dans les formules de calcul.

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +class eure_et_loir_aide_menagere_personne_agee(Variable):
L'objet de cette variable étant de calculer l'éligibilité, la convention est de faire figurer cet aspect dans le nom.
Dans ce dépôt, c'est indiqué après la zone géographique. Renommer la variable pour le faire figurer ?

```suggestion
class eure_et_loir_eligibilite_aide_menagere_personne_agee(Variable):
```

> Remarques auxiliaires : 
> L'éligibilité est plutôt en suffixe sur `openfisca-france` ; nous avons donc une petite incohérence là-dessus 😕 
> D'après le RDAS, c'est d'abord une aide sociale à domicile puis, elle est mise en oeuvre au travers de l'aide-ménagère à domicile et, finalement, est spécifique aux personnes âgées. Ca me semble un peu long à faire figurer dans le nommage 😅

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +    reference: Titre 2 Chapitre 1-1 Article 23 du Règlement départemental d'Aide Sociale PA PH de l'Eure et Loir
Pour chaque paramètre, ajouter un champ `description: ce que le paramètre représente`.

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +  taux_incapacite_maximum_avec_restriction_acces_emploi:
> [optionnel] Possibilité de raccourcir le nom en enlevant le `avec_`, voire`restriction_` ou `acces_` si cela ne semble pas ambigu 🤔  (la description aide à ceci aussi).

2020-11-26 20:37 UTC, sandcha commented on tests/departements/eure_et_loir/aide-menagere-personne-agee.yml
> +- name: Cas passant avec personne > 65 ans
`Cas passant` me semble ambigu pour le nommage d'un test. Remplacer `passant` par `éligible à l'aide...` ?

2020-11-26 20:37 UTC, sandcha commented on tests/departements/eure_et_loir/aide-menagere-personne-handicap.yml
> +    eure_et_loir_aide_menagere_personne_handicap: 0
```suggestion
    eure_et_loir_aide_menagere_personne_handicap: 0

```

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +    def formula_2020_01(individu, period,parameters):
👍 Pour la datation !

2020-11-26 20:37 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        individual_resource_names = {
👏 pour le principe de regroupement des éléments considérés pour la base de ressources !

2020-11-26 21:06 UTC, sandcha commented
Complément d'information : les conditions d'éligibilité données en description de cette PR concernent l'aide sociale à domicile pour l'aide-ménagère aux personnes âgées.

Les conditions d'éligibilité de l'aide sociale à domicile pour l'aide-ménagère aux **personnes handicapées** sont les suivantes (src : tableau aides) : 

```
• Etre reconnu à un taux d’incapacité supérieur ou égal à 80% ou à un taux d’incapacité compris entre 50 et 70% et présenter une restriction substantielle et durable pour l’accès à l’emploi
• Etre âgé de moins de 60 ans
• Etre de nationalité française ou réfugié ou apatride ou ressortissant de l’Union Européenne ou résident en France métropolitaine de manière ininterrompue depuis au moins 15 ans
• Ressources (hors pensions alimentaires, prestations familiales, retraite du combattant, pensions attachées aux distinctions honorifiques) inférieures à l’ASPA
```

Les montants de ces deux aides n'est pas calculable car, dans les deux cas, la décision est prise par le Président du Conseil départemental et la notification effectuée par la MDA comprend un nombre d'heures par mois [d'aide-ménagère d'après l'évaluation de l'équipe médico-sociale], les dates de prise en charge ainsi que la participation horaire laissée à la charge du bénéficiaire. 
> Src : RDAS, pages 20 et 53.

2020-11-30 09:58 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        ressortissant_eee =  individu('ressortissant_eee', period)
Question en cours côté métier

2020-11-30 09:58 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        return condition_age * condition_nationalite * condition_gir * condition_ressources * conditions_aides
Question en cours côté métier

2020-12-04 18:34 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +aide_menagere:
Fait. Merci @CecileIAEGI !

2020-12-07 20:24 UTC, sandcha requested changes
Merci @CecileIAEGI pour les correctifs ! 
Il reste quelques éléments à propager sur l'ensemble : 
* l'opérateur `*` à la place de `and`
* il me semble, la même base ressources pour PH que pour PA
* et, a priori, le calcul de l'ASPA (pas de paramètre pour son montant mais l'appel de la variable)

Ainsi qu'une vérification des parenthèses sur les conditions (en lien avec les opérateurs).
Enfin, c'est ok pour les tests 🙌  
> Nous pourrons factoriser si tu le souhaites à l'avenir.

2020-12-07 20:24 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                    period).departements.eure_et_loir.aide_menagere.taux_incapacite_minimum_restriction_acces_emploi and restriction_substantielle_durable))
Ajouter des parenthèses autour des conditions pour éviter l'erreur : `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` ?

2020-12-07 20:24 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                             period).departements.eure_et_loir.aide_menagere.age_minimal_personne_agee_inapte_travail and inapte_travail))
Et, ajouter des parenthèses autour de la 2ème condition d'âge (c'est à dire, sur la condition précédant `inapte_travail`). En leur absence, ce test erroné se terminerait sans erreur : 
```yaml
- name: Test erroné car personne trop jeune
  period: 2020-10
  input: 
    nationalite: FR
    gir: gir_5
    asi_aspa_base_ressources_individu: 200
    depcom: 28000
  output:
    age: 50
    eure_et_loir_eligibilite_aide_menagere_personne_agee: True
```

2020-12-08 08:30 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                             period).departements.eure_et_loir.aide_menagere.age_minimal_personne_agee_inapte_travail and inapte_travail))
N'est-ce pas plutôt False qui doit ressortir si le test est erroné ?

2020-12-08 10:56 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        individual_resource_names = {
Comme vu ensemble, on garde la base générale pour les PA par rapport à la loi même si dans les faits c'est plutôt uniquement des retraites.
Pour les Ph, le métier m'a donné c'est ressources précises à prendre en compte

2020-12-08 10:56 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                age <= parameters(period).departements.eure_et_loir.aide_menagere.age_minimal_personne_handicap)
Vu avec le métier c'est bien <=

2020-12-08 10:57 UTC, CecileIAEGI commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +        value: 0.7
Corrigé, c'est bien 79% c'est une erreur de ma part

2020-12-23 18:17 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir.yml
> +aide_menagere:
> @CecileIAEGI Fait en visio mais non pushé sur GitHub ? 🤔

2020-12-23 20:23 UTC, sandcha requested changes
Merci pour l'ajout du non cumul PA 🙌 
Il y a  une dernière demande de modification sur cet ajout, principalement pour corriger un calcul à ce sujet et ajouter le non cumul pour le cas PH.

2020-12-23 20:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_age = (age <= parameters_chemin.age_minimal_personne_handicap)
> Strictement inférieur ? 🤔 À voir avec le métier. Le RDAS dit "L'aide-ménagère est accordée aux personnes de moins de 60 ans."

2020-12-23 20:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_nationalite = ressortissant_eee + individu('refugie',period) + individu('apatride', period)
Un mémo pour les futurs développements ? 

```suggestion
        condition_nationalite = ressortissant_eee + individu('refugie', period) + individu('apatride', period)
        # condition non intégrée : Les personnes de nationalité étrangère doivent justifier d'une résidence
        # en France métropolitaine ininterrompue depuis au moins 15 ans, et ce avant l'âge de 70 ans.
```

2020-12-23 20:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_ressources = individu_resources < individu.famille('aspa', period)
> Inférieur ou égal ? 🤔 
> Le RDAS dit : "Les ressources u demandeur ne doivent pas dépasser le montant de l'Allocation...(ASPA)"
> 

```suggestion
        condition_ressources = individu_resources <= individu.famille('aspa', period)
```

2020-12-23 20:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        return condition_residence * condition_taux_incapacite * condition_age * condition_nationalite * condition_ressources
Ajouter les règles de non-cumul ? (RDAS pages 54-en-haut/50-en-bas)

```suggestion
        condition_aides_actp = not_(possede_actp)
        condition_aides_mtp = not_(possede_mtp)
        condition_aide_menagere_caisse_retraite = not_(individu('aide_menagere_fournie_caisse_retraite', period.last_month))
        conditions_non_cumul = condition_aide_menagere_caisse_retraite * condition_aides_actp * condition_aides_mtp
        return condition_residence * condition_taux_incapacite * condition_age * condition_nationalite * conditions_non_cumul * condition_ressources
```

2020-12-23 20:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        return condition_residence * condition_taux_incapacite * condition_age * condition_nationalite * condition_ressources
Pour PA/PH, nous avons `aide_menagere_fournie_caisse_retraite` d'après le mois précédent. Il me semble que ce pourrait être "pas d'aide ménagère actuellement/au mois courant". As-tu vu la référence au mois précédent dans un règlement ou avec les référents métier ? 🤔

2020-12-23 23:18 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/caracteristique_socio_demographique.py
> +class actp(Variable):
Indiquer qu'il s'agit de l'éligibilité dans le nom de la variable, par convention ?
```suggestion
class eligibilite_actp(Variable):
```

2021-01-04 08:16 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_age = (age <= parameters_chemin.age_minimal_personne_handicap)
Vu avec le métier, c'est bien strictement inférieur

2021-01-04 08:20 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_apa = individu('apa_domicile', period.last_month) <=0
Le soucis que j'ai c'est que ce n'est pas que je ne peux pas prétendre à l'aide ménagère si je suis éligible à l'apa.
c'est je ne peux pas prétendre à l'aide ménagère si je Bénéficie de l'apa. 

Pour moi être éligible et être bénéficiaire ce n'est pas la même chose donc en prenant la valeur apa_domicle, on vérifie qu'elle est à 0, que la personne soit éligible à l'apa ou non

2021-01-04 08:51 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        return condition_residence * condition_taux_incapacite * condition_age * condition_nationalite * condition_ressources
Je pense que tu as raison c'est plutôt le mois courant

2021-01-04 09:15 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_aide_menagere_caisse_retraite = False if individu('aide_menagere_fournie_caisse_retraite',period.last_month) else True
corrigé avec not_

2021-01-07 18:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_apa = individu('apa_domicile', period.last_month) <=0
Ok. Bien vu !

2021-01-07 18:55 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_age = (age <= parameters_chemin.age_minimal_personne_handicap)
Sauf erreur de ma part, l'opérateur n'a pas été mis à sa valeur stricte. Le mettre à jour ?

2021-01-07 19:03 UTC, sandcha approved these changes
Bravo pour tout ce travail ! 🚀

2021-01-08 11:17 UTC, sandcha commented
@CecileIAEGI Mise à jour de cette branche vis-à-vis de la branche `master` en cours.
Je mets aussi à jour le numéro de version puis merge 🙌

2021-01-08 11:27 UTC, merged

2021-01-21 15:31 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_ressources = individu('asi_aspa_base_ressources_individu', period) <= individu.famille('aspa', period)
À la revue d'une autre PR (#76), je réalise que l'[asi_aspa_base_ressources_individu](https://fr.openfisca.org/legislation/asi_aspa_base_ressources_individu) contient les pensions alimentaires `pensions_alimentaires_percues`. 
Or, d'après le RDAS sur l'aide ménagère PA (page 19 notation haute/du pdf), elles sont à exclure du calcul. 
@CecileIAEGI Soustraire `pensions_alimentaires_percues` de la base de ressources dans une futur PR ?