Eure et loir ash
openfisca/openfisca-france-local pull request #71
Opened 2020-11-23 09:36 UTC by CecileIAEGI

**### Ajout des aides ASH de l'Eure-et-Loir**

Les conditions d'attributions de l'aides ASH sont les suivantes :
 **Pour les personnes âgées :** 

-  Etre âgé de plus de 65 ans ou de plus de 60 ans en cas d’inaptitude au travail
-  Etre de nationalité française ~~ou réfugié ou apatride~~ ou ressortissant de l’Union Européenne ou bénéficiaire d’un titre de séjour
-  Ressources ~~(dont celles des obligés alimentaires)~~ inférieures aux frais d’hébergement (= loyer établissement)

 **Pour les personnes en situation de handicap :** 

- 	Etre âgé de 18 ans et plus
- 	Etre de nationalité française ~~ou réfugié ou apatride~~ ou ressortissant de l’Union Européenne ou bénéficiaire d’un titre de séjour
- 	Bénéficier d’une reconnaissance de situation de handicap

2020-11-26 22:14 UTC, sandcha requested changes
Merci @CecileIAEGI ! 
Quelques remarques de forme similaires à celles de la PR des aides ménagères + casse minuscules des noms de fichiers et paramètres.
Revue des tests à venir après la mise à jour des opérateurs :)

2020-11-26 22:14 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                                     or (taux_incapacite< parameters(period).departements.eure_et_loir.aide_menagere.taux_incapacite_maximum_avec_restriction_acces_emploi and taux_incapacite>paramete
```suggestion
                                     + (taux_incapacite < parameters(period).departements.eure_et_loir.aide_menagere.taux_incapacite_maximum_avec_restriction_acces_emploi * taux_incapacite > parameters(period).departements.eure_et_loir.aide_menagere.taux_incapacite_minimum_avec_restriction_acces_emploi * restriction_substantielle_durable))
```

2020-11-26 22:14 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +                """
```suggestion
    reference = [
        "Titre 2 Chapitre 1-1 du Règlement départemental d'Aide Sociale PA PH de l'Eure-et-Loir",
        "https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RDAS_valide__decembre_2019.pdf"
    ]
    documentation = """ 
    L’aide-ménagère est une aide en nature accordée aux personnes âgées qui, du fait de leur état de santé ou de leur âge, ont besoin de recourir à un personnel pour effectuer les actes de la vie courante. La participation financière du bénéficiaire est définie par le Conseil départemental.
    L’éligibilité de l’aide dépend niveau de GIR (5 ou 6).
    Cette aide fait l’objet d’une récupération sur succession et n’est pas cumulable avec l’Allocation compensatrice pour tierce personne (ACTP), la Majoration Tierce Personne (MTP versée par la CPAM), l’Allocation personnalisée d’autonomie (APA), les prestations d’aide-ménagère servie par les caisses de retraite.
    """
```

2020-11-26 22:14 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/ASH.py
> +                                 period).departements.eure_et_loir.ASH.age_minimal_personne_agee_inapte_travail and inapte_travail))
Employer les [opérateurs compatibles avec le calcul vectoriel](https://openfisca.org/doc/coding-the-legislation/25_vectorial_computing.html#boolean-operations)? 
Factoriser le parcours de l'arbre des paramètres commun ? 
Et indenter en fonction des opérations ? 
> Le cas inapte_travail est-il bien parenthésé ? Sera vérifié à la revue des tests :) 
```suggestion
        ash_parameters = parameters(period).departements.eure_et_loir.ASH
        condition_age = (
            (age >= ash_parameters.age_minimal_personne_agee_apte_travail)
            + (age >= ash_parameters.age_minimal_personne_agee_inapte_travail * inapte_travail)
            )
```

2020-11-26 22:14 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/aide-menagere.py
> +        condition_gir = ((gir == TypesGir.gir_5) or (gir == TypesGir.gir_6))
Dans l'ensemble, mettre à jour les opérateurs pour employer `+` en place de `or`, `*` pour le `and` et `not_(...)` en place du `not` avec l'import qu'il nécessite en haut de fichier. 😊

2020-12-23 17:31 UTC, sandcha requested changes
Merci @CecileIAEGI. 
Demande de changement principalement sur un bug de cumul de retraites.

2020-12-23 17:31 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +        condition_ressources = individu_resources <= individu.menage('loyer', period)
Est-ce 100% des ressources qui sont pris en compte ? 🤔 
La page ASH du site [service-public](https://www.service-public.fr/particuliers/vosdroits/F2444), dans sa section `Montant`, indique que 90% des ressources sont prises pour l'hébergement en établissement. Il semble probable que la condition d'attribution corresponde avec l'usage final de la somme pour le loyer (en supposant que l'information soit valide au niveau du département).

2020-12-23 17:31 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/caracteristiques_socio_demographiques.py
> +    label = "La personne est réfugié"
Reconnu au niveau administratif, non ? 🤔 
```suggestion
    label = "La personne dispose du statut de réfugié"
```

2020-12-23 17:31 UTC, sandcha commented on openfisca_france_local/parameters/departements/eure_et_loir/ash.yml
> +  age_minimal_personne_handicap:
> Par cohérence avec "agee", noter "handicapee" ?

2021-01-05 08:37 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +            'retraite_imposable'
En vérifiant dans le questionnaire de mes-aides.org sur lequel on doit se baser, je ne garde que la retraite_nette car c'est celle qui y est demandé.
J'ai également rajouté (en consultant le RDAS) la rentre viagère, les pensions alimentaires perçues, les revenus de capital

2021-01-05 08:40 UTC, guillett commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +            'retraite_imposable'
@CecileIAEGI la valeur de la retraite brute est estimée sur le simulateur, c'est fait [ici](https://github.com/mes-aides/simulateur/blob/master/backend/lib/openfisca/mapping/individu/ressources.js#L22-L28). Si le règlement de l'Eure-et-Loir fait référence à des montants bruts il est préférable de garder ça, selon moi.

2021-01-05 08:43 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +            'retraite_imposable'
et également les revenus locatifs

2021-01-05 08:44 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +        condition_ressources = individu_resources <= individu.menage('loyer', period)
J'ai ajouté les revenus qui me semblaient être accessible aux personnes âgées.
Initialement, je n'avais mis que la retraite car le contact métier m'avait dit que les PA n'avaient que ce type de ressources

2021-01-05 08:51 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +            'retraite_imposable'
Le règlement est vraiment flou sur ce point là, il est juste inscrit ressources de la personne.
Du coup ça veut dire que dans le simulateur c'est bien la retraite brute qui est prise en compte et non la nette ?

2021-01-05 09:01 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +        condition_ressources = individu_resources <= individu.menage('loyer', period)
en fait comme c'est un minimum de ressources, je suppose que si la PA a d'autres ressources que la retraite, en pratique elle dépasse le montant autorisé et donc n'a pas accès à l'aide

2021-01-14 18:56 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/ash.py
> +        condition_ressources = individu_resources <= individu.menage('loyer', period)
> Pardon, j'entendais que nous avons potentiellement : 
`(0.9 * individu_resources) <= individu.menage('loyer', period)`
Pourra être corrigé dans une autre PR au besoin.

2021-01-14 19:38 UTC, sandcha approved these changes
👍 Merci @CecileIAEGI pour ces deux aides !
Il me semble que cette PR correspond bien à notre niveau de connaissance actuel concernant les ressources à prendre en compte. 

Il me paraît probable que nous revenions dessus ultérieurement, quand nous en saurons plus. Par exemple, nous ne prenons pas les ressources du conjoint et les personnes à charge mais il y a un faisceau d'indices qui y font référence 🔎  comme sur [cette page d'Eure-et-Loir](https://www.vernouillet28.fr/solidarite-sante/action-solidaire/conseil-soutien-accompagnement/aide-sociale-hebergement) ou la section `Montant` de [la page dédiée service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F2444) et que nous n'avons pas encore clarifié la proportion des ressources de l'[Article L132-3](https://www.legifrance.gouv.fr/codes/id/LEGISCTA000006157562/2021-01-14/) mais ceci peut venir en amélioration continue 🙂 

@guillett Quelques discussions semblent encore ouvertes. Reste-t-il des modifications à apporter ?

2021-01-20 16:05 UTC, sandcha commented
Pour les personnes âgées, les ressources du conjoint ne sont pas prises en compte parce que le tableau de l'Eure-et-Loir exclue pour le moment les ressources des obligés alimentaires : 
Ressources (~~dont celles des obligés alimentaires~~) inférieures aux frais d’hébergement (= loyer établissement)

A priori, ce choix a été pris en raison de la complexité de l'identification de ces ressources et de leur association à des variables existantes d'openfisca-france.

2021-01-20 18:32 UTC, sandcha commented
Rebase en cours.

2021-01-20 18:44 UTC, merged

2021-01-20 18:48 UTC, sandcha commented
Merci @CecileIAEGI @guillett 🙌 
Suite à l'échange de cette après-midi, les ASH sont mergées mais n'hésitez pas à intégrer les résultats de la discussion restée ouverte dans une prochaine PR s'il restait quelque chose à modifier.