Eure et loir pch
openfisca/openfisca-france-local pull request #72
Opened 2020-11-23 09:39 UTC by CecileIAEGI

### **Ajout des aides PCH de l'Eure-et-Loir**

Les conditions d'attributions des aides OCH sont les suivantes : 
**PCH à domicile :** 

-  Etre de nationalité française ~~ou réfugié ou apatride~~ ou ressortissant de l’Union Européenne ou bénéficiaire d’un titre de séjour
-  Bénéficier d’une reconnaissance de situation de handicap
-  Non cumulable avec l’Allocation compensatrice pour tierce personne (ACTP), l’Allocation personnalisée d’autonomie (APA) et l’Allocation d’éducation de l’enfant handicapé (AEEH)

**PCH en établissement :** 

-  Etre de nationalité française ~~ou réfugié ou apatride~~ ou ressortissant de l’Union Européenne ou bénéficiaire d’un titre de séjour
-  Bénéficier d’une reconnaissance de situation de handicap
- Etre en situation d’hospitalisation ou d’hébergement en établissement social ou médico-social

2020-12-23 23:11 UTC, sandcha commented
@CecileIAEGI Pour la **PCH à domicile**, le descriptif en en-tête de cette PR correspond parfaitement bien à ce qui a été résumé dans le tableau Eure-et-Loir mais comprend quelques incohérences avec le RDAS. 

En particulier : 

1. Le non cumul avec l'AEEH est dans le RDAS et [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F14809) un non cumul avec le `Complément à l'AEEH`, complément décrit dans le même [article](https://www.legifrance.gouv.fr/codes/id/LEGIARTI000006743351/2005-02-12/) du code de la sécurité sociale que l'allocation de base AEEH.
2. Le non cumul avec ACTP est, dans le RDAS, décrit avec le non cumul ACFP. Or, celui-ci n'est pas barré dans le tableau Eure-et-Loir. Oubli ?
3. La condition d'âge n'est pas citée quand dans le RDAS, elle est associée à différentes situations (moins de 20 ans + AEEH, plus de 60 ans + ACTP, ...). Choix ou oubli ? 🤔 

Les 2 et 3 peuvent être complétées ultérieurement. La 1 me semble plus source d'erreur. 
À confirmer / vérifier avec le métier ?

2020-12-23 23:51 UTC, sandcha requested changes
👍 Code très clair 

Demande de changement pour le même bug que pour les aides ménagères (correctif proposé). 

Et, dans un premier temps, je serais en faveur d'une intervention sur deux incohérences tableau Eure-et-Loir/RDAS : à domicile, Complément AEEH au lieu d'AEEH + en établissement, ajout de PCH domicile antérieure avant. 

@CecileIAEGI, j'ai conscience que cela équivaut à une incohérence de spécifications pour ce livrable ; voir le moment le plus opportun aussi pour toi pour leur vérification/traitement.

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        possede_apa = individu('apa_domicile', period) > 0
Utiliser l'éligibilité à l'APA pour éviter un calcul supplémentaire de montant ?
```suggestion
        possede_apa = individu('apa_eligibilite', period)
```

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        possede_actp = individu('actp', period)
> Le nom de la variable `actp` n'est-il pas ambigu ? `bénéficiaire_actp` sinon ? Par convention, je ne m'attendrais pas à un booléen pour ce nom. 🤔

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        condition_aides_actp = False if possede_actp else True
De même que pour les aides ménagères (cf. [ce commentaire](https://github.com/openfisca/openfisca-france-local/pull/69#discussion_r548159738)), correctif pour intégrer l'aspect vectoriel des données manipulées : 
```suggestion
        condition_aides_aeeh = not_(possede_aeeh)
        condition_aides_apa = not_(possede_apa)
        condition_aides_actp = not_(possede_actp)
```
Avec cet import déjà suggéré plus haut : 
```py
from openfisca_france.model.base import not_
```

> Ce code peut aussi être factorisé en réduisant le nombre de variables intermédiaires / calculant directement dans le `not_`.

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +from openfisca_france.model.base import Variable, Individu, MONTH
En complément d'une remarque plus bas dans ce fichier.
```suggestion
from openfisca_france.model.base import Variable, Individu, MONTH, not_
```

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        possede_aeeh = individu.famille('aeeh', period) > 0
D'après le RDAS, il s'agirait du Complément à l'AEEH. Ajouter une variable le représentant et amender cette ligne avec ?

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +    def formula_2020_01(individu, period):
👍 Formule en phase avec le descriptif du tableau Eure-et-Loir.

2020-12-23 23:51 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        return condition_residence * condition_nationalite * condition_handicap * condition_hebergement
De même que pour la PCH à domicile, la PCH en établissement hériterait des incohérences si je saisis bien cette phrase du RDAS (page 88-en-haut/84-en-bas) : 

<img width="982" alt="Screen Shot 2020-12-24 at 00 40 18" src="https://user-images.githubusercontent.com/6567910/103044407-a61d4a80-4580-11eb-8e6d-0c837de6bf3d.png">

➕ Une condition supplémentaire d'attribution qui me semble être d'avoir bénéficié de la PCH à domicile :

<img width="995" alt="Screen Shot 2020-12-24 at 00 38 29" src="https://user-images.githubusercontent.com/6567910/103044364-84bc5e80-4580-11eb-9ac2-6449a6d37548.png">
Ajouter cette dernière condition ? Qu'en dis-tu ? 🤔

2020-12-23 23:51 UTC, sandcha commented on tests/departements/eure_et_loir/pch_etablissement.yml
> +    eure_et_loir_eligibilite_pch_etablissement: False
Ajout d'un retour à la ligne 🙂 
 
```suggestion
    eure_et_loir_eligibilite_pch_etablissement: False

```

2021-01-07 08:23 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        possede_apa = individu('apa_domicile', period) > 0
Comme pour les aides ménagères, pour moi être éligible et être bénéficiaire, ce n'est pas la même chose.
On peut être éligible à une aide mais ne pas la demander. Or apa_eligibilite ne fait que retester si la personne est éligible à apa. Elle ne vérifie pas si la personne est réellement bénéficiaire de l'appa

2021-01-07 08:37 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        possede_aeeh = individu.famille('aeeh', period) > 0
Je suis d'accord avec toi, dans le RDAS, c'est bien avec le complément AEEH qu'il faut comparer.
En revanche dans le doc client, c'est bien AEEH.
Je vais mettre complement aeeh car pour moi c'est ce qui correspond au RDAS et à ce que j'avais lu à propos de l'AEEH.

2021-01-07 08:47 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        return condition_residence * condition_nationalite * condition_handicap * condition_hebergement
ça me parait compliqué à rajouter car comme condition car pour moi c'est le binome (ne sort jamais de l'établissement + ne bénéficiait pas avant de la PCH) qui s'applique.

2021-01-15 12:21 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        return condition_residence * condition_nationalite * condition_handicap * condition_hebergement
Ceci dit, si on ne fait pas référence à la PCH à domicile comme prérequis à la PCH en établissement, il me semble qu'il manque à minima les mêmes conditions de non cumul dans la formule de la PCH en établissement.
Vérifier le tout avec le métier pour une prochaine PR ?

2021-01-15 12:38 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        return condition_residence * condition_nationalite * condition_handicap * condition_hebergement
Oui en effet, je pense que tu as raison pour les règles de non cumul avec l'aeeh et l'actp pour la PCH à domicile
Je vais les rajouter.
Malheureusement je ne peux pas vraiment contacter le métier parce que officiellement ma mission avec le CD28 est terminée. Donc je me abse sur ce qui est inscrit dans le RDAS et lorsque la suite de la mission commencera (si elle commence) je pourrais demander au métier si on a encore besoin.

2021-01-15 12:39 UTC, sandcha approved these changes
Merci @CecileIAEGI 🙂 
Je joins deux propositions de changement non bloquantes.
Par ailleurs, comme indiqué en commentaire, il me semble qu'il manque a minima les règles de non cumul pour la PCH en établissement ou son lien avec la PCH à domicile pour une prochaine PR selon ce que dira le métier !
En tout cas, bon pour merge après rebase et versionnement !

2021-01-15 12:39 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        #condition_aides_aeeh = not_(individu.famille('aeeh', period) > 0)
Eviter le code commenté qui vieillit mal dans le temps ? Les échanges de cette PR seront là pour nous rappeler pourquoi nous avons privilégié le complément sur aeeh ^^
```suggestion

```

2021-01-15 12:39 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        condition_aides_actp = not_(individu('beneficiaire_actp', period)) * not_(individu('beneficiaire_acfp',period))
`condition_aides_actp` n'est-il pas ambigu quand il représente aussi bien l'ATCP (allocation compensatrice pour tierce personne) et l'ACFP (allocation compensatrice frais professionnels) ? Renommer ?

Pour le contexte, il semble que la PCH remplace l'[ACTP](https://www.service-public.fr/particuliers/vosdroits/F2475) et l'[ACFP](https://www.service-public.fr/particuliers/vosdroits/F1657) depuis 2006 sans les interrompre pour les bénéficiaires qui l'avaient déjà d'après cet [article](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000006682332) (loi 2005-102).

2021-01-15 12:57 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        condition_aides_actp = not_(individu('beneficiaire_actp', period)) * not_(individu('beneficiaire_acfp',period))
les gens qui lisent le code vont voir que c'est actp + acfp.
Est-ce réellement nécessaire de renommer sachant que acfp va avec le temps disparaitre complètement ?

2021-01-15 14:14 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        condition_aides_actp = not_(individu('beneficiaire_actp', period)) * not_(individu('beneficiaire_acfp',period))
C'est que la formule restera dans le temps.

2021-01-15 14:35 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/pch.py
> +        condition_aides_actp = not_(individu('beneficiaire_actp', period)) * not_(individu('beneficiaire_acfp',period))
si tu préfères je peux faire une petite mise à jour et mettre conditions_aides_actp_acfp ?

2021-01-20 16:13 UTC, sandcha commented
Lien entre PCH à domicile et la PCH en établissement n'a pas été ajouté à ce stade afin de représenter les deux aides au niveau du simulateur. À compléter ultérieurement au besoin.

2021-01-20 19:37 UTC, sandcha commented
Rebase en cours.

2021-01-20 19:50 UTC, merged