Eure et loir transports
openfisca/openfisca-france-local pull request #73
Opened 2020-12-01 13:13 UTC by CecileIAEGI

Cette branche contient les aides suivantes :

 **Carte mobilité inclusion « invalidité » (CMI invalidité)**  dont les conditions sont les suivantes :

- Etre reconnu à un taux d’incapacité supérieur ou à égal à 80% 
- **ou** être bénéficiaire de l’Allocation personnalisée d’autonomie (APA) ~~et~~ classé en GIR 1 ou en GIR 2
- ~~ou être bénéficiaire d’une pension d’invalidité de 3ème catégorie~~
- Résider en Eure-et-Loir

 **Carte mobilité inclusion « stationnement » (CMI stationnement)** dont les conditions sont les suivantes :
- Bénéficiaire de l’Allocation personnalisée d’autonomie (APA) **et** classé en GIR 1 ou GIR 2
- Résider en Eure-et-Loir

**Transport des élèves et étudiants en situation de handicap**  dont les conditions sont les suivantes : 
- Etre élève ou étudiant
- Bénéficier d’une reconnaissance de situation de handicap
- Résider en Eure-et-Loir

Les conditions barrées ne sont pas prise en compte pour au sein du calcul d'éligibilité à ces 3 aides

2020-12-07 13:14 UTC, CecileIAEGI commented
L'aide suivante a également été ajoutée : 

**Carte mobilité inclusion « priorité » (CMI priorité)** dont les conditions sont les suivantes :
- Etre reconnu à un taux d’incapacité inférieur à 80%
- Reconnaissance de la station debout pénible
- Etre de nationalité française ou ressortissant UE ou réfugié ou apatride ou bénéficiaire titre de séjour
- Résider en Eure-et-Loir 

La condition de Nationalité a été rajouté sur les 3 aides de type CMI

2021-01-06 18:39 UTC, sandcha requested changes
Merci pour ces 4 aides ! 
Principale demande de correction : `if` non adapté au calcul vectoriel et présent dans deux formules. 

Il y a également une condition d'invalidité pour la CMI-stationnement manquante si on se fie au RDAS. Ceci pourrait être ajouté dans une autre PR si validé par le contact métier.

> En grisé des éléments qui comme toujours sont optionnels / compléments d'information transverse aux aides.

2021-01-06 18:39 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/transport_eleves_etudiants.py
> +    label = "En Eure-et-Loir,éligibilité à l'aide au Transport des élèves et étudiants en situation de handicap"
Typo 
```suggestion
    label = "En Eure-et-Loir, éligibilité à l'aide au Transport des élèves et étudiants en situation de handicap"
```

2021-01-06 18:39 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/transport_eleves_etudiants.py
> +        etudiant = individu('etudiant', period) # individu('etudiant', period) regroupe les 2 activités : étudiant ET élève
👍 pour la précision. On peut enlever le code en commentaire qui, similaire à ce qui précède, peut faire penser à un résidu de debug.

```suggestion
        etudiant = individu('etudiant', period) # regroupe les 2 activités : étudiant ET élève
```

2021-01-07 09:01 UTC, CecileIAEGI commented on openfisca_france_local/parameters/departements/eure_et_loir/transports.yml
> +cmi_invalidite:
J'ai regroupé les 2 taux en un seul : taux_incapacité_minimal qui concerne les 2 aides

2021-01-07 09:09 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/cmi_priorite.py
> +        conditions_taux_incapacite = individu('taux_incapacite', period) <= parameters_chemin.taux_incapacite_minimal
d'après le rdas qui nous renvoi au guide barème, ça serait bien strictement inférieur.
donc j'ai mis < 0.80 au lieu de <=0.8

2021-01-07 09:12 UTC, CecileIAEGI commented on tests/departements/eure_et_loir/cmi_priorite.yml
> +        taux_incapacite: 0.79
Le choix de 0.79 était juste pour mettre un taux inférieur à 80 %.
C'est vrai que le barème ne parle pas de ce qui se passe entre 75% et 80 % mais mes contacts métiers m'ont bien expliqué qu'il n'y a pas de "trous".
Je change par 0.74 comme ça pas de soucis ^^

2021-01-20 16:17 UTC, CecileIAEGI commented on openfisca_france_local/departements/eure_et_loir/cmi_stationnement.py
> +        return condition_nationalite * condition_residence * condition_apa * condition_gir
Cet condition n'a pas été rajoutée car il n'existe à l'heure actuelle par de variable représent la difficulté à marcher ni dans le modèle ni dans le simulateur mes-aides.org

2021-02-01 17:09 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/cmi_stationnement.py
> +        return condition_nationalite * condition_residence * condition_apa * condition_gir
En attendant l'ajout de la précision (ou pas) du côté du simulateur, nous pouvons ajouter une condition et la bouchonner à la requête du simulateur s'il n'y a pas de champ sur son interface graphique. Ainsi, cela permettra, via une autre PR, de couvrir la définition de la CMI stationnement (qui n'est a priori pas accordée si la handicap n'affecte pas la capacité de marcher 🤔).

2021-02-01 17:15 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/cmi_stationnement.py
> +        return condition_nationalite * condition_residence * condition_apa * condition_gir
@guillett Une question à venir pour le simulateur : 
La condition `le handicap réduit de manière importante et durable la capacité et l'autonomie de déplacement à pied, ou qui impose l'accompagnement d'une tierce personne dans les déplacements` nécessaire à la `carte mobilité inclusion - stationnement` a-t-elle vocation à être dans les questions à l'usager ou en précision dans le résultat de la simulation ?

2021-02-01 17:18 UTC, guillett commented on openfisca_france_local/departements/eure_et_loir/cmi_stationnement.py
> +        return condition_nationalite * condition_residence * condition_apa * condition_gir
Pour le moment, c'est le genre de condition qu'on peut afficher sur la page de résultats en tant que « condition textuelle ». Dans ce cas là, le plus simple c'est de mettre cette variable par défaut à `True` pour afficher l'aide sans imposer un ajout de cette variable-là à vrai côté simulateur.

2021-02-01 17:20 UTC, sandcha approved these changes
Merci pour les correctifs !
Cela me semble ok pour l'aspect vectoriel. Seule limitation identifiée : pour la CMI stationnement, la difficulté à se déplacer n'est pas intégrée dans les conditions d'attribution.

Rebase et merge en cours.

2021-02-01 17:56 UTC, merged