Eure et loir fsl
openfisca/openfisca-france-local pull request #75
Opened 2020-12-03 10:03 UTC by CecileIAEGI

Cette branche contient les aides FSL de l'Eure-et-Loir. 
Les aides ajoutées sont présentées ci-dessous ainsi que leurs conditions associées

**Fonds de solidarité pour le logement (FSL) – Accès au logement** : 
- Ressources inférieures ou égales à 60% du seuil de pauvreté ~~(ressources hors aide personnelle au logement, allocation logement, allocation de rentrée scolaire, allocation d’éducation spéciale et ses compléments)~~
 => La liste des ressources à prendre en compte se trouve à la page  du règlement intérieur (https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RI_FSL28_2020_valide_AD_16.12.2019.pdf)
- Résider en Eure-et-Loir

**Fonds de solidarité pour le logement (FSL) – Installation dans le logement** : 
- Ressources inférieures ou égales à 60% du seuil de pauvreté ~~(ressources hors aide personnelle au logement, allocation logement, allocation de rentrée scolaire, allocation d’éducation spéciale et ses compléments)~~
 => La liste des ressources à prendre en compte se trouve à la page  du règlement intérieur (https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RI_FSL28_2020_valide_AD_16.12.2019.pdf)
- Résider en Eure-et-Loir

**Fonds de solidarité logement (FSL) – Maintien dans le logement** : 
- Etre locataire ou propriétaire 
- Ressources inférieures ou égales à 60% du seuil de pauvreté ~~(ressources hors aide personnelle au logement, allocation logement, allocation de rentrée scolaire, allocation d’éducation spéciale et ses compléments)~~
 => La liste des ressources à prendre en compte se trouve à la page  du règlement intérieur (https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RI_FSL28_2020_valide_AD_16.12.2019.pdf)
- Résider en Eure-et-Loir

**Fonds de solidarité logement (FSL) – Maintien des fournitures  « Energie-Eau-Téléphone »** : 
- Etre locataire ou propriétaire 
- Ressources inférieures ou égales à 60% du seuil de pauvreté ~~(ressources hors aide personnelle au logement, allocation logement, allocation de rentrée scolaire, allocation d’éducation spéciale et ses compléments)~~
 => La liste des ressources à prendre en compte se trouve à la page  du règlement intérieur (https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RI_FSL28_2020_valide_AD_16.12.2019.pdf)
- Résider en Eure-et-Loir

2021-01-18 11:11 UTC, sandcha commented
@CecileIAEGI À quelle page du règlement intérieur fais-tu référence dans la description de cette PR stp ? 🙂 
Ceci pour identifier la description de la base de ressources / le socle de `eure_et_loir_ressources_menage_inférieure_seuil_pauvrete_60`.

2021-01-18 12:26 UTC, CecileIAEGI commented
@sandcha pour les aides FSL on se base sur le règlement intérieur des FSL :
https://github.com/openfisca/openfisca-france-local/wiki/files/departements/eure-et-loir/RI_FSL28_2020_valide_AD_16.12.2019.pdf

la liste des ressources à prendre en compte est en Annexe P45 de ce règlement intérieur.

2021-01-18 22:07 UTC, sandcha requested changes
Merci @CecileIAEGI pour ces aides et pour la définition de leur base de ressources riche d'information 😅 
Principale demande de changement : remplacer quelques `if` par une syntaxe vectorielle et des éléments complémentaires à la base de ressources.

2021-01-18 22:07 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +        if is_en_couple[0]:
Utiliser une syntaxe vectorielle comme indiqué dans les PR précédentes ? 
La situation d'une famille ne peut pas être utilisée pour toutes les familles. 😊

2021-01-18 22:07 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +        condition_ressources = True if menage_resources <= seuil_pauvrete else False
De même, adapter à la syntaxe vectorielle puisque le même booléen ne peut faire sens pour tous les ménages de la simulation. ^^

2021-01-18 22:13 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +            'asf',
> La liste de la page 45 règlement évoque également `Autres prestations sociales`. Il semble alors que la liste détaillée de vienne que représenter les cas les plus courants et que l'ensemble pourrait être représenté par la variable [prestations_sociales](https://fr.openfisca.org/legislation/prestations_sociales) recouvrant aussi bien l'`af`, que les `al` etc. 🙃

2021-01-18 22:20 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +            'alf',
En utilisant `apl` et `alf` (deux des 3 composantes de l'[aide_logement](https://fr.openfisca.org/legislation/aide_logement)), n'avons-nous pas choisi l'aide logement complète et donc plutôt la variable aide_logement ? 🤔 
Le règlement indiquant `Aides aux logements versées au ménage (AL/APL)`, je m'attendrais à `apl` seul ou à toutes les aides avec `aide_logement`.

2021-01-19 08:39 UTC, CecileIAEGI commented on openfisca_france_local/parameters/departements/eure_et_loir/fsl.yml
> +  en_0:
J'avais essayé de cette manière là mais cela ne voulait pas fonctionner correctement donc j'avais trouvé cette solution là.
Préfères-tu que je refasse comme tu proposes ici ? 
J'avais du faire des erreurs qui faisaient que cela ne fonctionnait pas comme souhaité.

2021-01-19 08:40 UTC, CecileIAEGI commented on openfisca_france_local/parameters/departements/eure_et_loir/fsl.yml
> +  en_0:
Est-ce que je mets enfant_0 ou bien nbenfant_0 ?

2021-01-20 15:15 UTC, sandcha commented
Reste à ajouter l'[AJPP](https://www.service-public.fr/particuliers/vosdroits/F15132) à openfisca-france et à indiquer la référence de la branche openfisca-france où elle figurera.

2021-01-20 15:23 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +        if is_en_couple[0]:
Utiliser [numpy.where](https://numpy.org/doc/1.18/reference/generated/numpy.where.html?highlight=where#numpy.where) ?

2021-02-01 18:24 UTC, sandcha commented
Bonjour @CecileIAEGI, Je vois que tu as fait quelques 👍 sur des discussions de revue mais qu'il n'y a pas de nouveau commit. En aurais-tu en réserve sur ton ordinateur ? 😁

2021-02-24 11:53 UTC, sandcha commented on openfisca_france_local/departements/eure_et_loir/fsl.py
> +            'indemnites_journalieres',
Non appliqué en raison de la section "Autres" ressources du règlement.

2021-02-24 12:08 UTC, sandcha approved these changes
Comme convenu, j'ai appliqué les éléments de la revue + supprimé le doublon FSL en réforme et cela me semble prêt à être mergé.
La base de ressources sera néanmoins à vérifier en amélioration continue parce que le tableau en annexe du règlement (page 45) a été indiqué comme référence des ressources à prendre en compte par le métier mais qu'il contient beaucoup d'éléments, une section "Autres" et les aides au logement/ars qui seraient à exclure selon les critères d'éligibilité (page 19). De plus, l'ajpp est à ajouter à openfisca-france.

2021-02-24 12:21 UTC, merged